In [ ]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

import pandas as pd
import openai

### Read sampled dataset with Amazon inventory data

In [2]:
df_items = pd.read_json("../../data/meta_Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines=True)

In [3]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Camera & Photo,80x100 Monocular-Telescope Low Night Vision Mo...,3.6,187,[],[],29.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': '80X100 monocular telescope high po...,MANDDDWU,"[Electronics, Camera & Photo, Binoculars & Sco...",{'Product Dimensions': '3.94 x 3.94 x 3.94 inc...,B09YHBXZC8,NaN,NaN,NaN
1,All Electronics,"SoundPEATS Air Conduction Headphones, RunFree ...",4.0,132,[𝗨𝗻𝗯𝗲𝗮𝘁𝗮𝗯𝗹𝗲 𝗖𝗼𝗺𝗳𝗼𝗿𝘁 𝗮𝗻𝗱 𝗟𝗶𝗴𝗵𝘁𝘄𝗲𝗶𝗴𝗵𝘁 𝗗𝗲𝘀𝗶𝗴𝗻 - 🍀...,[],29.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Soundpeats RunFree Lite - The Best...,SoundPEATS,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '7.48 x 5.16 x 2.13 inc...,B0BRXDR9GF,NaN,NaN,NaN
2,Computers,"𝟮𝟬𝟮𝟯 𝗟𝐚𝐭𝐞𝐬𝐭 Tablet 10.1"" Octa-Core Android 11 ...",4.3,411,[【VALUE FOR MONEY】Get all the bundled accessor...,[],179.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'The most complete tablet bundle', ...",FEONAL,"[Electronics, Computers & Accessories, Compute...","{'Standing screen display size': '10.1', 'Scre...",B0B4C98K37,NaN,NaN,NaN
3,Tools & Home Improvement,"120PCS 6 Inch Reusable Cable Ties, Wire Ties, ...",4.8,647,[Super Valuable: 120PCS cable straps is enough...,[],8.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': '120PCS Black Reusable Cable Ties',...",Mvyc,"[Electronics, Accessories & Supplies, Cord Man...","{'Manufacturer': 'Mvyc', 'Part Number': 'CAKF2...",B0B564JMB5,NaN,NaN,NaN
4,All Electronics,"CHIFENCHY 2 Packs Golf Speaker with Magnetic, ...",4.2,144,[GOLF PORTABLE BLUETOOTH SPEAKER: Designed in ...,[],99.98,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Honest Review of Ampcaddy Golf Blu...,CHIFENCHY,"[Electronics, Portable Audio & Video, Portable...",{'Product Dimensions': '3.74 x 1.57 x 3.54 inc...,B0BDYW4FC4,NaN,NaN,NaN

In [8]:
list(df_items["features"].items())[1]

(1,
 ['𝗨𝗻𝗯𝗲𝗮𝘁𝗮𝗯𝗹𝗲 𝗖𝗼𝗺𝗳𝗼𝗿𝘁 𝗮𝗻𝗱 𝗟𝗶𝗴𝗵𝘁𝘄𝗲𝗶𝗴𝗵𝘁 𝗗𝗲𝘀𝗶𝗴𝗻 - 🍀 𝘽𝙚𝙨𝙩 𝙑𝙖𝙡𝙪𝙚 𝙊𝙥𝙚𝙣-𝙚𝙖𝙧 𝙎𝙥𝙤𝙧𝙩 𝙃𝙚𝙖𝙙𝙥𝙝𝙤𝙣𝙚 - 𝘾𝙉𝙀𝙏 🍀. The RunFree Lite headset is carefully optimized for weight distribution, ensuring a secure and comfortable fit that eliminates worries of slipping and shaking. Wrapped in skin-friendly liquid silicone, these lightweight headphones (0.99oz) provide a weightless and comfortable experience for extended listening during gym sessions, exercise, running, and more.',
  '𝗢𝗽𝗲𝗻-𝗘𝗮𝗿 𝗗𝗲𝘀𝗶𝗴𝗻 𝗮𝗻𝗱 𝗗𝘆𝗻𝗮𝗺𝗶𝗰 𝗦𝗼𝘂𝗻𝗱 - Stay connected and aware of your surroundings with our open-ear design sports headphones, which use air conduction technology to enhance the aerodynamic transmission of sound, resulting in a more dynamic and powerful audio experience. Enjoy up to 17 hours of playtime on a single charge to keep your music going for daily and weekly exercises. Only 1-2 hours charge will get full energy back.',
  '𝗣𝗼𝘄𝗲𝗿𝗳𝘂𝗹 𝗕𝗮𝘀𝘀 𝗮𝗻𝗱 𝗦𝘁𝗮𝗯𝗹𝗲 𝗖𝗼𝗻𝗻𝗲𝗰𝘁𝗶𝗼𝗻 - Featuring the latest low-frequency enhancement technology and Bluetooth 5.3 transmission, our headphones offer a seamless audio experience with a significant reduction in distortion and enhanced sound quality. The built-in 16.2mm drivers with an open soundstage improve the sound further, delivering even more powerful bass for a truly immersive audio experience.',
  '𝗖𝗿𝘆𝘀𝘁𝗮𝗹-𝗖𝗹𝗲𝗮𝗿 𝗖𝗮𝗹𝗹𝘀 𝗮𝗻𝗱 𝗗𝗶𝗿𝗲𝗰𝘁𝗶𝗼𝗻𝗮𝗹 𝗦𝗼𝘂𝗻𝗱 - Experience crystal-clear audio with our directional sound transmission technology that significantly reduces sound leakage. Equipped with a dual-beamforming microphone array featuring a noise reduction optimization algorithm, which isolates and enhances your voice while filtering out background noise, making phone calls and video conferences feel like face-to-face conversations.',
  "𝗦𝘄𝗲𝗮𝘁𝗽𝗿𝗼𝗼𝗳 𝗮𝗻𝗱 𝗠𝘂𝗹𝘁𝗶𝗽𝗼𝗶𝗻𝘁 𝗖𝗼𝗻𝗻𝗲𝗰𝘁𝗶𝗼𝗻 - The RunFree Lite headset is IPX4-rated and equipped with an anti-sweat design, making it perfect for carefree exercise and outdoor activities in all weather conditions. It can also pair with two devices simultaneously, allowing for seamless multitasking. For more personalized features, download and register the SoundPEATS App. (📱: The App supports upgrading the firmware. 🎯 Note: Please rest assured, the headphone works very well if you don't want to download and register the App.)"])

In [9]:
list(df_items["images"].items())[1]

(1,
 [{'thumb': 'https://m.media-amazon.com/images/I/31OGeYLIfnL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/31OGeYLIfnL._AC_.jpg',
   'variant': 'MAIN',
   'hi_res': 'https://m.media-amazon.com/images/I/51IIaSHi-JL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41UxJVxZl2L._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41UxJVxZl2L._AC_.jpg',
   'variant': 'PT01',
   'hi_res': 'https://m.media-amazon.com/images/I/71y+++taYRL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51yay41lk+L._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51yay41lk+L._AC_.jpg',
   'variant': 'PT02',
   'hi_res': 'https://m.media-amazon.com/images/I/71K+bE7AN0L._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/410gEVmQuAL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/410gEVmQuAL._AC_.jpg',
   'variant': 'PT03',
   'hi_res': 'https://m.media-amazon.com/images/I/61+OhVOzGxL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41Ca45+LCoL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41Ca45+LCoL._AC_.jpg',
   'variant': 'PT04',
   'hi_res': 'https://m.media-amazon.com/images/I/61GMUlbPxqL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41vsxEZNUUL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41vsxEZNUUL._AC_.jpg',
   'variant': 'PT05',
   'hi_res': 'https://m.media-amazon.com/images/I/61UEazu5AiL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41TqNyk-MaL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41TqNyk-MaL._AC_.jpg',
   'variant': 'PT06',
   'hi_res': 'https://m.media-amazon.com/images/I/71otRWr3QzL._AC_SL1500_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/31+d6UGL+YL._AC_US40_.jpg',
   'large': 'https://m.media-amazon.com/images/I/31+d6UGL+YL._AC_.jpg',
   'variant': 'PT07',
   'hi_res': 'https://m.media-amazon.com/images/I/51AgZhAldbL._AC_SL1500_.jpg'}])

### Preprocess title and features

In [10]:
def preprocess_desciption(row):
        return f"{row['title']} {' '.join(row['features'])}"


def extract_first_large_image(row):
        return row['images'][0].get('large', '')


df_items["description"] = df_items.apply(preprocess_desciption, axis=1)
df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

In [14]:
df_items.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,image
0,Camera & Photo,80x100 Monocular-Telescope Low Night Vision Mo...,3.6,187,[],80x100 Monocular-Telescope Low Night Vision Mo...,29.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': '80X100 monocular telescope high po...,MANDDDWU,"[Electronics, Camera & Photo, Binoculars & Sco...",{'Product Dimensions': '3.94 x 3.94 x 3.94 inc...,B09YHBXZC8,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51Ni+NLJS4...
1,All Electronics,"SoundPEATS Air Conduction Headphones, RunFree ...",4.0,132,[𝗨𝗻𝗯𝗲𝗮𝘁𝗮𝗯𝗹𝗲 𝗖𝗼𝗺𝗳𝗼𝗿𝘁 𝗮𝗻𝗱 𝗟𝗶𝗴𝗵𝘁𝘄𝗲𝗶𝗴𝗵𝘁 𝗗𝗲𝘀𝗶𝗴𝗻 - 🍀...,"SoundPEATS Air Conduction Headphones, RunFree ...",29.99,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Soundpeats RunFree Lite - The Best...,SoundPEATS,"[Electronics, Headphones, Earbuds & Accessorie...",{'Package Dimensions': '7.48 x 5.16 x 2.13 inc...,B0BRXDR9GF,NaN,NaN,NaN,https://m.media-amazon.com/images/I/31OGeYLIfn...
2,Computers,"𝟮𝟬𝟮𝟯 𝗟𝐚𝐭𝐞𝐬𝐭 Tablet 10.1"" Octa-Core Android 11 ...",4.3,411,[【VALUE FOR MONEY】Get all the bundled accessor...,"𝟮𝟬𝟮𝟯 𝗟𝐚𝐭𝐞𝐬𝐭 Tablet 10.1"" Octa-Core Android 11 ...",179.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'The most complete tablet bundle', ...",FEONAL,"[Electronics, Computers & Accessories, Compute...","{'Standing screen display size': '10.1', 'Scre...",B0B4C98K37,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51HfEQ1Osc...
3,Tools & Home Improvement,"120PCS 6 Inch Reusable Cable Ties, Wire Ties, ...",4.8,647,[Super Valuable: 120PCS cable straps is enough...,"120PCS 6 Inch Reusable Cable Ties, Wire Ties, ...",8.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': '120PCS Black Reusable Cable Ties',...",Mvyc,"[Electronics, Accessories & Supplies, Cord Man...","{'Manufacturer': 'Mvyc', 'Part Number': 'CAKF2...",B0B564JMB5,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51+jacwzqi...
4,All Electronics,"CHIFENCHY 2 Packs Golf Speaker with Magnetic, ...",4.2,144,[GOLF PORTABLE BLUETOOTH SPEAKER: Designed in ...,"CHIFENCHY 2 Packs Golf Speaker with Magnetic, ...",99.98,[{'thumb': 'https://m.media-amazon.com/images/...,[{'title': 'Honest Review of Ampcaddy Golf Blu...,CHIFENCHY,"[Electronics, Portable Audio & Video, Portable...",{'Product Dimensions': '3.74 x 1.57 x 3.54 inc...,B0BDYW4FC4,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51+uS0y5fA...

In [21]:
len(list(df_items['description'].items()))

1000

### Sample 50 items from this dataset

In [22]:
df_simple = df_items.sample(50, random_state=42)

In [23]:
len(df_simple)

50

In [37]:
data_to_embed = df_simple[['description', 'image', 'rating_number', 'price', 'average_rating', 'parent_asin']].to_dict(orient="records")

In [52]:
data_to_embed

[{'description': "USB C Hub, MCY USB C to HDMI Multiptort Adapter, 10 in 1 Portable Type C Dongle with 4K HDMI, VGA, PD Charging, USB 3.0 and USB 2.0 Ports, SD/TF Card, Compatible with MacBook, HP, Dell and More 【10 IN 1 USB C Docking Station】MCY Type-C smart docking station can solve 10 kinds of office troubles at one time. USB C hub multiport adapter hub rich interface. HDMI makes the big screen clearer. 1G files are transferred in 3 seconds, and there is no need to wait for the transfer. 【Wonderful more than one side】10-port USB C to HDMI adapter turns your laptop into a thin and light desktop computer. It is equipped with 4K@60Hz HDMI port, VGA port, SD/TF card reader and USB 3.0 and USB 2.0 ports. Get rid of the problem of insufficient notebook ports and connect more devices. A Type C interface helps you upgrade your space. 【4K Video HDMI to USB C Hub】Mirror or extend your laptop/tablet/phone's screen with hdmi port and directly stream 4K@60Hz (3840 x 2160) or full HD 1080P lifelike video to monitor, projector and HDTV, this usb c to hdmi adapter hub can bring you an immersive 3D resolution experience. 【Ultra-fast and massively expandable】The usb c expansion hub with high-speed 4 USB-A ports, capable of fast data transfer at 5Gb/s transfer speed and expand more external usb devices such as: U-disk, hard drive, mouse, keyboard. Built in SD/TF card slot for easy access to files from SD and Micro SD memory card readers for USB-C/Type-C/Thunderbolt 3 devices. (Note: USB 3.0 Port doesn't support charging) 【Broad Compatibility】Our docks have excellent compatibility, just plug and play, no additional drivers required. Compatible with MacBook Pro 2016 2017 2018, New MacBook Air 2018-(Not for previous generation MacBook Air & Pro), MacBook 12, New iMac/Pro, Surface Book 2/Go, iPad Pro (2020 / 2018), Chromebook, Pixelbook, Dell, HP, Huawei mate 20/P20, Samsung S8/S8 Plus/S9/S9 Plus/S10, more fully-functional Type C devices. (See Product Description)",
  'image': 'https://m.media-amazon.com/images/I/41KhTIzecrS._AC_.jpg',
  'rating_number': 358,
  'price': nan,
  'average_rating': 4.6,
  'parent_asin': 'B0BTYK7SB3'},
 {'description': 'JBL GO 3 Waterproof Ultra Portable Bluetooth Speaker Bundle with Megen Hardshell Case (Black) SPECIAL BUNDLE - Includes, JBL GO 3 Portable Bluetooth Speaker and, Megen Hardshell Travel Case. JBL Pro Sound delivers super big audio and punchy bass from Go 3’s ultra-compact size. IP67 WATER AND DUSTPROOF - A full-featured IP67 waterproof and dustproof Bluetooth speaker to take with you everywhere with a Shockproof Megen Case. JBL Go 3’s ultra-portable design goes great with the latest styles, and its design make it look as great as it sounds. Output Wattage : 4.2 Watts Power Source Type : Battery Powered PERFECT PAIR - The Megen Case’s soft velvet interior protects the speaker and integrated mesh pocket is designed perfectly for accessories and Shockproof so you keep it safe.',
  'image': 'https://m.media-amazon.com/images/I/51dNK8wHt7L._AC_.jpg',
  'rating_number': 129,
  'price': 48.95,
  'average_rating': 4.7,
  'parent_asin': 'B09ZWNVYV2'},
 {'description': "AuviPal USB C Coupler (2 Pack), USB Type C Female to Female Adapter Extender Compatible with Thunderbolt 4/3 Support up to 40Gbps Data Transfer, 100W Power Delivery and 8K@60Hz Video Pass Through This adapter allows you to join two shorter USB C cables together when you need to extend the length of a USB-C cable for fast charge, data transfer or video pass through. Supports blind insertion of USB C cable due to the exclusive built-in USB4 transmission protocol chip, Eliminating the need to reverse the orientation of cable's each plug. (NOTE: If your cable is USB2.0 Standard, you need to reverse the orientation of cable's each plug for working properly) Compliant with the latest USB 4 and Thunderbolt 4 standard, backward compatibility. Support up to 40Gbps data transfer, 100W power delivery and 8K@60Hz video pass through, this adapter will give you a longer cable without any sacrifice. Premium aluminium alloy shell for durable service, easy to carry or store due to the ultra compact design, the two USB C female connectors Passes 10,000+ push and pull tests. Plug and play, no driver or software required, Simply plug it in, then it is ready to go.Matters Need Attention: If your cable is USB2.0 Standard, you need to reverse the orientation of cable's each plug for working properly.",
  'image': 'https://m.media-amazon.com/images/I/41eXtbyQkbL._AC_.jpg',
  'rating_number': 120,
  'price': 9.99,
  'average_rating': 4.0,
  'parent_asin': 'B0B8X7R7PT'},
 {'description': 'Talkpod A36Plus GMRS Handheld Two Way Radio Walkie Talkies for Adults Long Range with VHF UHF Receive, 5W Output, 512 Channels, 1.44inch Color Screen(Green) Tx Range (MHz): 462/467MHz, Rx Range (MHz): 136-180 FM/AM VHF 230-250 FM/AM VHF 350-400 FM/AM UHF 400-512 FM/AM UHF 512 Channels (Each A/B has 256) Dual-Band Analog FM HAM (Amateur Radio Service) Two-Way Transceiver V/V,U/U,V/U Dualwatch, Pre-Programmed for HAM Tru-Power VHF 5/2/0.5 Watts, UHF 5/2/0.5 Watts IP54 Water Jets Rated Extended-Capacity 3200mAh (23.68 Wh) Li-ion Battery (*Optional TBL12). FCC ID: 2ADQZGMRS1 with Part 15B and Part 95E Wide 7-Band Receive Range with AM AIR Band & Broadcast FM Radio (w/ 20 Memories) Memory & VFO Modes (Tx locked to HAM frequencies) Wide & Narrow Bandwidth DTMF Keypad Repeater Reverse & Talk-Around Functions 50 CTCSS PL Tones & 105 DCS Privacy Codes (Independently Front-Panel Programmable) CTCSS/DCS Scanning. 1.44 inch Color Display, 16 Full Keypad (w/ Auto-Lock), 2 Programmable Function Side-Keys, 2.5 kHz Tuning Steps, SOS Emergency Top Button, Battery Saver Time-Out-Timer (w/ alarm), 8-Character Alpha Channel Names, Type-C Connector Voice Announce (English or Chinese) & Key Beeps (optional) 10 Squelch Levels BCL, VOX, SideTones, DTMF & ANI PTT-ID, Roger Beep 8″. High-Gain Dual-Band Antenna Tuned for HAM Bands (removable) Wrist Strap Belt Clip English Manual Full Line of Accessories.',
  'image': 'https://m.media-amazon.com/images/I/51J3UgEPHKL._AC_.jpg',
  'rating_number': 103,
  'price': nan,
  'average_rating': 3.8,
  'parent_asin': 'B0C37T5TPS'},
 {'description': "MingSung MS25 4K Camera Video Sunglasses, 4K Video and Photo, Easy Wear Sports Action Camera for Biking, Skiing, Motorcycling, Fishing, Travelling(Include 32G MicroSD Card) 4K ULTRA HD CAMERA: MingSung MS25 sunglasses have a built-in 4K camera, which captures super clear videos and pictures. It is a 1080P camera that can't do. Perfect for your outdoor sports. INCLUDE MEMORY CARD: No extra buy, no extra cost. MingSung MS25 video recording sunglasses come with a high-speed Micro SD card. It has been plugged into the card slot. You can start your shooting immediately when you get it. EASY TO USE: Camera with sunglasses, one second to wear on your head. Just press the right side button for 3 seconds to start recording. Quick take video and picture, never lost your beautiful moment. LONG WORKING TIME: MingSung MS25 video sunglasses built-in a rechargeable battery, it can be recording video for about 90 minutes on a full charge. The battery life is over 5 years. PERFECT GIFT FOR MEN: Cool electronic gadgets, the perfect gift for Dad and husband. Film the beautiful and funny moments hands-free when you are playing with family and friends. Widely used for traveling, parties, Disney Park, roller coaster, climbing, biking, fishing, scouting, camping, driving, hunting, skateboarding, motorcycle, Etc.",
  'image': 'https://m.media-amazon.com/images/I/31dOnxqkjqL._AC_.jpg',
  'rating_number': 210,
  'price': 69.99,
  'average_rating': 4.5,
  'parent_asin': 'B0C615MZ5N'},
 {'description': '4G GPS smart watch for boy girl 3-15 years old Kids Global Real-Time tracking watches Waterproof Cell Phone watch Child Video Chat Device SOS Alarm Camera Geo-Fence Pedometer Anti-Lost Tracker Locator 💎 [Multi functions kids smart watch with gps tracker and calling]: The main functions of the kids phone watch include Real Time GPS Position, phone call, video call, SOS Call, Voice Chat, Camera, Photo album, Phone Book, Alarm Clock, Class Mode, Safety Fence, Pedometer, Historical Route etc. This kids gps watches is a perfect Christmas Birthday gift for your girls and boys. 💎 [Waterproof smart watch for kids 8-12]: The waterproof kids smart watch 8-12 can be worn in shower or rain. The kids smart watch 7-12 manufacturer is TEZILON. The smart watches for kids compatible in 3 - 15 years old boys and girls. The 4G kids smart watch boys gps and calling support SIM card：Speedtalk, T-mobile, US Mobile/etc. 💎 [Global smart watch for kids with calling & Anti-Lost kids gps watch]: The child gps tracker has a built-in GPS positioning device, a superb choice for personal safety. You can track your kids location in real time anywhere, anytime. Historical Route Track：Past locations of the tracker watch for kids in latest 1 month will be stored in system for your future checking. We offer lifetime free service for Android and IOS application software. This kids smart watch with gps tracker and calling can work very well in all countries. 💎 [Two-Way Phone call kids phone watch & Video call camera watch]: Besides serving as a tracker for kids, these kid tracker can also work as a cell phone to make phone calls and video calls. The phone watch for kids supports 4G SIM card. When you go to SIM operator stores, sales guys may tell you our 4g gps watch cannot support their SIM cards. No worries about this, if you make sure the SIM is with data plan and voice feature, just contact us immediately, we can help you get the watch worked at once. 💎 [Geo-fence & SOS Emergency Call ]: You can set a safe area centering around the watch wearer, the kids gps tracker watch will automatically raise an alarm in your phone application once the watch wearer leaves the area. You can also track multiple kids smart watch at the same time. SOS emergency phone call: The one-button SOS design, when encountering danger, Long-press the SOS button, it will automatically dial the emergency contact number. This emergency smart watch is undoubtedly a good tool. 💎 [IMPORTANT OF The kids 4G GPS Smart Watch]: This kids phone watch supports 4G network, while most kids watch GPS on Amazon support only 2G network. 2G network has been shut down in America, and you must get this watch with 4G compatibility that works perfectly in America. This is the reason why our price is higher than other kids call watch, 4G GPS watch needs much cost on the chip.',
  'image': 'https://m.media-amazon.com/images/I/51mca8szCJL._AC_.jpg',
  'rating_number': 138,
  'price': 89.99,
  'average_rating': 3.9,
  'parent_asin': 'B0BZM8YN4K'},
 {'description': "Soundcore by Anker Space A40 Auto-Adjustable Active Noise Cancelling Wireless Earbuds, Reduce Noise by Up to 98%, 50H Playtime, Hi-Res Sound, Comfortable Fit, App Customization, Wireless Charge Reduce Noise By Up to 98%: Space A40 has an upgraded noise cancelling system to block out a wider range of distracting noises. So wherever you go, you'll always have the space you need to focus. Automatically Tailored Noise Cancelling: Space A40 detects external noises and automatically selects a suitable level of noise cancelling for your surroundings. Enjoy your personal space whether you're indoors, outdoors, commuting, or on a flight. 50 Hours of Personal Space: That's enough playtime to enjoy up to 1,000 songs or 25 movies. The earbuds have a 10-hour single charge playtime, and fast charging gives you 4 hours of listening from a quick 10-minute charge. Highly Detailed Sound: Thanks to soundcore's pioneering double-layer diaphragm drivers, Space A40 noise cancelling earbuds produce sound with strong bass, clear mids, and bright treble. You can also listen using LDAC mode for Hi-Res Audio Wireless sound. Comfortable, No Matter How Long You Listen: Space A40 noise cancelling wireless earbuds are smaller than all other soundcore ANC earbuds, are as light as a sheet of paper, and have an ergonomic shape so they fit comfortably in your ears.",
  'image': 'https://m.media-amazon.com/images/I/31o9tGssVUL._AC_.jpg',
  'rating_number': 3008,
  'price': 79.0,
  'average_rating': 4.3,
  'parent_asin': 'B0BJ9PRHZ3'},
 {'description': "iPhone Fast Charger, [Apple MFi Certified] 20W PD Type C Power Wall Charger with 3FT Lightning Cable Compatible with iPhone 13/13 Pro Max/12/12 Mini/12 Pro/12 Pro Max/11/11 Pro iPad AirPods 💌[One Charger, Lifetime Service] At Hcoob, you don't have to worry about after-sales problems, if you have any problems with the product, please let us know at any time, we will give you a satisfactory solution, we have confidence in our products and we are responsible to customers. 💪[3FT Apple Lightning Cable] The iphone charger sets includes 1*3 foot type c to lightning cable and apple 20W fast charger, which can charge your multiple apple devices and the charging speed is up to 3A. Let you spend less time used for charging and have more space for activities when it charge. Quick connect and High speed Data Transfer speed up to 480Mb/s helps you work efficiently. 👍[Orginal iphone High Speed Charger] Equipped with USB C Power Delivery port, PD 3.0 quick charge USB C port provides max 20w output power , latest-generation, future-proof fast charging technology, no error message pops up and works perfectly with your device while charging fast, 4X faster than regularly chargers. 💯[Applicable Apple Equipment] 100% With for iPhone13/13 mini/13 Pro/13 ProMax/iPhone 12/12 mini/12 Pro/12 ProMax/iPhone 11 ProMax/ 11 Pro/11/iPhone XS/ XS Max/ XR/ X/iPhone 8 Plus/ 8/iPhone SE 2020/iPad at fast speed , and charges for iphone 7Plus/7/6s Plus/6s/6Plus/6/5s/5/SE at an original charging speed. It also works with other USB C devices. ✅[Apple 20w Charger,Safety Assurance] Hcoob's ucb c fast charger built-in safety protection, which can monitor temperature and voltage in real time, maximize the protection of your device. The charger has a smart chip inside that actively adjusts the power output according to the needs of the device. As the battery is fully charged, the charging speed will be slower to give the battery time to absorb the charge and prevent the battery from rupturing.",
  'image': 'https://m.media-amazon.com/images/I/3149HsGm0qL._AC_.jpg',
  'rating_number': 802,
  'price': 9.71,
  'average_rating': 4.5,
  'parent_asin': 'B0C6KVXZH9'},
 {'description': 'Galaxy Tab A8 10.5" Keyboard Case 2022, FOGARI 7 Colors Backlit Detachable Bluetooth Keyboard Slim Folio Smart Cover for Samsung Galaxy Tab A8 10.5 Inch - Black ✅ 【Compatibility】 - This Galaxy Tab A8 keyboard case will turn your Galaxy into a stylish laptop in Seconds. It is compatible with Samsung Galaxy Tab A8 10.5 Inch 2022 Model (SM-X200/X205/X207). It will NOT work for any other model device. Please kindly check the model number SM-T*** at the Setting before purchase. ✅【Detachable & Backlit Bluetooth Keyboard】- 3 levels of brightness and 7 vibrant colors make typing fun and easy in the dark or the light.The Galaxy Tab A8 keyboard can be attached to the case magnetically, if not needed, it can be removed.Bluetooth connectivity is easy. ✅【 Full Body Protection】- Premium composition leather exterior protects your tablet from accidental dropping and bumps;Soft anti-slip interior protects your tablet from being scratched.Three dents on the case for propping up the tablet into three different viewing angles in landscape mode.Perfect for working, writing, or watching videos. ✅【Auto Sleep/ Wake Function】- It automatically wakes or puts your tablet to sleep when it is opened or closed,save much power for your Samsung Galaxy Tab A8.The Precise cutouts allows easy access to all features. ✅【Package & Warranty - content includes】- 1 x keyboard case for Samsung Galaxy Tab A8 10.5 Inch 2022, 1 x Micro USB charging cable,1 x user Manual.★★★ We provides you with 24-hour email contact service & 1-year worry-free warranty &30-day money-back guarantee.',
  'image': 'https://m.media-amazon.com/images/I/51FrZZpP3UL._AC_.jpg',
  'rating_number': 143,
  'price': 33.99,
  'average_rating': 4.4,
  'parent_asin': 'B09TSX4YVQ'},
 {'description': "Case Compatible with Apple 2023 Mac Mini M2/ Mac Mini M1 & Mac Mini Previous Model Desktop Computer, Electronics Organizer Fits for Keyboard, Magic Mouse and Accessories (Box Only)-Gray Electronics Organizer Perfect Fits: For apple desktop travel case is designed for apple 2023 mac mini desktop computer m2 chip/ for mac mini m1 and mac mini previous models. For mac mini case fits for Apple magic/ for logitech mx master 3s / for HP X3000 G2/ for Uiosmuph G12/ for Logitech B100 / Logitech M170 corded and wireless mouse. For apple mac mini m2 bag external size: 12.6*9.44*3.54 inches, inter size 7.87*7.87*1.97 inches (for mac mini computer), 3.35*7.87*1.97 inches (for mouse). Multiple Collection for Apple Computer Mac mini Box: 2023 mac mini m2 case has 5 different sizes mesh pockets. First layer is zipper mesh pockets, which stores AC power adapter cord; Second layer is used to collect for apple magic keyboard; And third layer is designed with 3 small mesh pockets, which storage electronic accessories such as hard drive, memory card, earphone and others. For mac mini m1 organizer keeps all in one place, so you don't have to rummage to find what you need. For Mac Mini Desktop Computer Holder Excellent Protection: For apple 2023 mac mini desktop computer bag made of hard EVA material, which is waterproof, shockproof, and scratch-resistant; With soft inner lining, mini m1 computer case can effectively protect for apple mac mini with apple M1 chip and internal accessories from scratches, dust, impacts and accidental drops. Double protection, for apple mac desktop storage keeps your precious mac mini in safe state. Easy to Carry Case for Apple Mac Mini M2: For mac mini travel box ingeniously combines handle and shoulder strap, which increases carrying choices. Smooth handle does not hurt your hands, and shoulder strap can be adjusted according to your needs. You can carry for mac mini m1 16gb ram container for travel, office or business trips. Sturdy and smooth double zipper makes it easy to open and close for apple mac studio organizer, brings better user experience. For M2 Mac Mini Case Home Companion: Portable case for 2023 mac mini is light and durable, which is companion for home, office, school and business. For apple pc protective bag is not only convenient to storage, but also ensures that your desk is always neat and tidy. For macbook mini case can be used as gift. If for mac mini 16gb box has any quality problem, we support 100% refund. Note: For sale is mac mini carrying case only, not include computer and accessories.",
  'image': 'https://m.media-amazon.com/images/I/510Qa86keZL._AC_.jpg',
  'rating_number': 111,
  'price': 31.99,
  'average_rating': 4.6,
  'parent_asin': 'B0B9HBDHKQ'},

### Define embedding function

In [46]:
from dotenv import load_dotenv
import os
import voyageai

load_dotenv()
VOYAGE_API_KEY = os.environ.get("VOYAGE_API_KEY")
vo = voyageai.Client(api_key=VOYAGE_API_KEY)

result = vo.embed(
    ["random data"],
    model="voyage-3",
    input_type="document"
)
embedding = result.embeddings[0]

In [47]:
embedding

[0.022841699421405792,
 -0.05015590041875839,
 0.00798660796135664,
 0.0023460660595446825,
 0.022681966423988342,
 0.06453179568052292,
 0.02779339626431465,
 0.00035440572537481785,
 0.005830223672091961,
 0.06325393915176392,
 -0.046002861112356186,
 0.014695358462631702,
 -0.06868483126163483,
 -0.008705402724444866,
 0.023800091817975044,
 0.033863216638565063,
 -0.057184115052223206,
 0.034981343895196915,
 0.07092107832431793,
 0.013896698132157326,
 -0.020126251503825188,
 0.030029647052288055,
 -0.04344714805483818,
 0.029550449922680855,
 -0.029710182920098305,
 0.017730269581079483,
 0.04823911190032959,
 0.010382590815424919,
 -0.013337635435163975,
 -0.0019367524655535817,
 -0.010542322881519794,
 -0.07124054431915283,
 -0.04440554231405258,
 -0.03881491348147392,
 0.005031562875956297,
 -0.03290482610464096,
 0.0027753463946282864,
 -0.03146723657846451,
 -0.02715446799993515,
 -0.06772643327713013,
 -0.025557145476341248,
 -0.024439020082354546,
 -0.051753219217061996,
 0.0041730026714503765,
 -0.04983643442392349,
 0.031147770583629608,
 0.006828549783676863,
 0.005670491605997086,
 -0.03258536010980606,
 -0.016851743683218956,
 -0.02092491276562214,
 -0.03338402137160301,
 -0.02667527087032795,
 0.050794828683137894,
 -0.04728072136640549,
 0.02108464576303959,
 -0.06005929410457611,
 0.03402294963598251,
 0.002096484648063779,
 -0.023320894688367844,
 0.019886653870344162,
 0.007427545730024576,
 0.056545186787843704,
 0.011740313842892647,
 -0.04248875379562378,
 -0.051433756947517395,
 0.025557145476341248,
 -0.023800091817975044,
 -0.0268350038677454,
 -0.0552673265337944,
 -0.003554040566086769,
 0.03370348736643791,
 -0.005271161440759897,
 0.005470826756209135,
 0.008745335973799229,
 -0.024279288947582245,
 -0.014855091460049152,
 -0.0015374220674857497,
 0.005710424855351448,
 0.03354375436902046,
 0.00022961497597862035,
 0.004811931401491165,
 -0.03945384547114372,
 -0.035141076892614365,
 -0.003154710168018937,
 0.011979912407696247,
 -0.018369197845458984,
 -0.015573885291814804,
 0.006109755020588636,
 0.009184598922729492,
 -0.0546283982694149,
 -0.04312768206000328,
 0.003094810526818037,
 0.03130750358104706,
 0.024918217211961746,
 -0.017890002578496933,
 -0.0051912954077124596,
 -0.014216162264347076,
 0.04344714805483818,
 0.02619607374072075,
 -0.014695358462631702,
 0.0032345762010663748,
 0.017330938950181007,
 0.014934957027435303,
 0.03210616484284401,
 -0.015334287658333778,
 0.004053203389048576,
 -0.025237681344151497,
 0.00970372837036848,
 0.013896698132157326,
 -0.015733618289232254,
 0.006029888987541199,
 0.009903393685817719,
 -0.02140410989522934,
 0.008705402724444866,
 -0.019487323239445686,
 0.01126111764460802,
 -0.01078192051500082,
 -0.013577233999967575,
 0.05973982810974121,
 -0.008505737408995628,
 0.03306455910205841,
 0.055906254798173904,
 -0.01677187718451023,
 0.0269947350025177,
 0.00485186418518424,
 0.008945001289248466,
 -0.03801625594496727,
 -0.03833571821451187,
 0.009024866856634617,
 0.010023193433880806,
 -0.012538975104689598,
 0.02156384103000164,
 -0.03881491348147392,
 0.0025057983584702015,
 0.06708750873804092,
 0.01078192051500082,
 0.03178669884800911,
 -0.023320894688367844,
 0.02172357402741909,
 -0.03290482610464096,
 0.013896698132157326,
 -0.02252223528921604,
 -0.012059777975082397,
 0.008186273276805878,
 0.030988039448857307,
 -0.02252223528921604,
 -0.0034741745330393314,
 -0.029230985790491104,
 0.0002395982446614653,
 -0.01661214418709278,
 -0.03226589784026146,
 -0.002895145444199443,
 -0.01581348478794098,
 0.035780005156993866,
 -0.03625920042395592,
 0.010302724316716194,
 -0.028272593393921852,
 0.028592057526111603,
 -0.02779339626431465,
 0.016532279551029205,
 -0.004951696842908859,
 0.046322327107191086,
 -0.01565375179052353,
 0.0005740374326705933,
 -0.05846197158098221,
 -0.01709134131669998,
 0.007826875895261765,
 0.026036342605948448,
 -0.007467478513717651,
 0.0274739321321249,
 0.013657099567353725,
 -0.030349111184477806,
 -0.006748683750629425,
 -0.029390716925263405,
 0.01070205494761467,
 0.015893349424004555,
 -0.013098036870360374,
 0.007387612480670214,
 0.012059777975082397,
 0.03817598521709442,
 -0.01613294892013073,
 -0.035620272159576416,
 0.00563055882230401,
 0.0012578907189890742,
 -0.04472500458359718,
 0.024758484214544296,
 -0.05782304331660271,
 0.013896698132157326,
 -0.029071252793073654,
 0.06580965220928192,
 -0.010622188448905945,
 -0.01924772560596466,
 0.015733618289232254,
 -0.04408607631921768,
 -0.0067886169999837875,
 -0.023959824815392494,
 -0.02188330702483654,
 -0.0008086440502665937,
 -0.024598753079771996,
 0.02220277115702629,
 0.050475362688302994,
 0.03849545121192932,
 0.016053082421422005,
 -0.014535626396536827,
 0.009424197487533092,
 0.017730269581079483,
 -0.022841699421405792,
 0.01860879734158516,
 -0.0523921474814415,
 0.023161163553595543,
 0.016532279551029205,
 0.029869914054870605,
 0.046002861112356186,
 0.006189621053636074,
 -0.012778572738170624,
 0.02236250229179859,
 0.019806787371635437,
 0.05973982810974121,
 0.02220277115702629,
 -0.03146723657846451,
 -0.045363932847976685,
 0.07635197043418884,
 -0.035300806164741516,
 0.005790290888398886,
 0.011101385578513145,
 0.0041730026714503765,
 0.022841699421405792,
 0.02252223528921604,
 0.010142992250621319,
 0.001197991194203496,
 -0.02220277115702629,
 -0.03881491348147392,
 0.010222858749330044,
 -0.0034342415165156126,
 -8.984933811007068e-05,
 -0.03402294963598251,
 0.04440554231405258,
 -0.035300806164741516,
 0.012778572738170624,
 -0.06421232968568802,
 0.011580581776797771,
 0.014375894330441952,
 -0.0005266169901005924,
 -0.03657866641879082,
 -0.056225720793008804,
 -0.03130750358104706,
 -0.0019167859572917223,
 -0.019008127972483635,
 -0.01725107431411743,
 0.06293447315692902,
 0.040092773735523224,
 -0.017890002578496933,
 -0.056864649057388306,
 0.034821610897779465,
 5.490793046192266e-05,
 0.039773307740688324,
 0.0002770354622043669,
 -0.023320894688367844,
 0.061976078897714615,
 0.01373696606606245,
 -0.018848394975066185,
 0.07156001031398773,
 -0.024279288947582245,
 -0.018369197845458984,
 0.012459108605980873,
 -0.003254542825743556,
 -0.034821610897779465,
 -0.06389286369085312,
 -0.0069084158167243,
 0.040252503007650375,
 -0.0022162836976349354,
 0.03178669884800911,
 0.020765181630849838,
 -0.013337635435163975,
 0.002555714687332511,
 0.01349736750125885,
 0.008146340027451515,
 0.04823911190032959,
 -0.017890002578496933,
 -0.00962386280298233,
 0.07603251188993454,
 0.008385938592255116,
 0.024758484214544296,
 0.023959824815392494,
 -0.035620272159576416,
 0.008346005342900753,
 -0.025557145476341248,
 -0.03354375436902046,
 -0.03657866641879082,
 0.029550449922680855,
 0.0005715416627936065,
 0.020206118002533913,
 0.039933040738105774,
 0.04791964963078499,
 -0.005870156921446323,
 0.023959824815392494,
 0.019966520369052887,
 -0.013018171302974224,
 -0.04344714805483818,
 -0.012459108605980873,
 -0.03162696957588196,
 0.06485125422477722,
 0.03801625594496727,
 0.010063125751912594,
 -0.010382590815424919,
 -0.055906254798173904,
 0.04121089726686478,
 0.0005241211620159447,
 -0.015893349424004555,
 0.02619607374072075,
 -0.040252503007650375,
 0.011101385578513145,
 0.024598753079771996,
 0.0008585603791289032,
 -0.015094689093530178,
 0.04440554231405258,
 0.023800091817975044,
 -0.002435915404930711,
 -0.04728072136640549,
 -0.0269947350025177,
 -0.015573885291814804,
 -0.02092491276562214,
 0.007307746447622776,
 0.04312768206000328,
 0.025557145476341248,
 0.015414153225719929,
 0.03338402137160301,
 -0.045363932847976685,
 0.01645241305232048,
 0.023161163553595543,
 0.01046245638281107,
 0.0008685436332598329,
 0.0025457313749939203,
 -0.0134175019338727,
 -0.007747009862214327,
 -0.005311094224452972,
 -0.005311094224452972,
 0.0017370872665196657,
 0.007108081132173538,
 -0.001856886432506144,
 -0.01597321592271328,
 -0.025557145476341248,
 -0.008745335973799229,
 0.019327592104673386,
 -0.04280821979045868,
 0.0274739321321249,
 0.025077950209379196,
 -0.012618840672075748,
 0.01940745674073696,
 5.39719985681586e-05,
 -0.02108464576303959,
 -0.013257769867777824,
 0.0035141075495630503,
 0.029071252793073654,
 0.0274739321321249,
 0.046002861112356186,
 -0.017570538446307182,
 -0.018528930842876434,
 0.0018069701036438346,
 -0.0029151118360459805,
 0.019647056236863136,
 0.005750357639044523,
 0.025397414341568947,
 -0.035141076892614365,
 -0.0263558067381382,
 0.006069822236895561,
 -0.015494019724428654,
 -0.01597321592271328,
 0.0004592299519572407,
 0.07539357990026474,
 0.03434241563081741,
 -0.06772643327713013,
 0.012139644473791122,
 0.016851743683218956,
 -0.02188330702483654,
 -0.018528930842876434,
 0.06772643327713013,
 0.04919750615954399,
 0.023001430556178093,
 0.06261500716209412,
 0.011340983211994171,
 0.035780005156993866,
 0.07315733283758163,
 -0.028432324528694153,
 0.020126251503825188,
 0.020046386867761612,
 7.48744514567079e-06,
 -0.01126111764460802,
 0.051753219217061996,
 -0.056864649057388306,
 -0.003693806240335107,
 0.008945001289248466,
 -0.009504063986241817,
 -0.023800091817975044,
 -0.005071496125310659,
 -0.01828933320939541,
 0.055906254798173904,
 0.02667527087032795,
 -0.05942036584019661,
 0.01645241305232048,
 -0.03849545121192932,
 0.0014775225427001715,
 -0.0552673265337944,
 -0.0012978238519281149,
 -0.03945384547114372,
 0.024119555950164795,
 -0.0269947350025177,
 0.04216929152607918,
 -0.012618840672075748,
 0.004712098743766546,
 -0.018848394975066185,
 0.0268350038677454,
 0.013018171302974224,
 0.029550449922680855,
 -0.0546283982694149,
 -0.024598753079771996,
 -0.04184982553124428,
 0.052072685211896896,
 -0.03258536010980606,
 -0.02188330702483654,
 0.041530363261699677,
 -0.03897464647889137,
 0.03130750358104706,
 0.06772643327713013,
 -0.013337635435163975,
 0.023959824815392494,
 0.003354375483468175,
 0.0552673265337944,
 0.035141076892614365,
 0.010182925499975681,
 0.03641893342137337,
 0.004592299461364746,
 0.06549018621444702,
 0.05973982810974121,
 -0.025077950209379196,
 -0.0017171207582578063,
 0.0051912954077124596,
 -0.03258536010980606,
 -0.02252223528921604,
 -0.08369965106248856,
 0.04472500458359718,
 -0.003094810526818037,
 -0.013098036870360374,
 -0.006429219618439674,
 0.01972692273557186,
 -0.03689812868833542,
 -0.023480627685785294,
 0.019167859107255936,
 0.019167859107255936,
 -0.035939738154411316,
 0.00465219933539629,
 -0.024918217211961746,
 -0.011580581776797771,
 0.028911521658301353,
 0.01629268005490303,
 0.03290482610464096,
 0.005311094224452972,
 -0.03370348736643791,
 -0.03801625594496727,
 -0.011420849710702896,
 0.011820180341601372,
 -0.010182925499975681,
 -0.04728072136640549,
 -0.030668575316667557,
 0.004592299461364746,
 0.03130750358104706,
 -0.019966520369052887,
 -0.02172357402741909,
 0.04696125537157059,
 0.024918217211961746,
 -0.051114290952682495,
 -0.004951696842908859,
 -0.009104733355343342,
 0.006668817717581987,
 -0.030349111184477806,
 0.00205655163154006,
 -0.0047320653684437275,
 -0.03306455910205841,
 0.010142992250621319,
 0.046002861112356186,
 0.025077950209379196,
 -0.011900045908987522,
 -0.02667527087032795,
 0.04376661404967308,
 -0.00043427181662991643,
 0.04696125537157059,
 0.04121089726686478,
 0.0021464009769260883,
 0.0025756810791790485,
 0.028592057526111603,
 0.041530363261699677,
 0.026036342605948448,
 0.014775224961340427,
 0.007387612480670214,
 -0.04919750615954399,
 -0.010861787013709545,
 -0.013098036870360374,
 -0.01956718973815441,
 -0.06772643327713013,
 0.039613574743270874,
 0.014775224961340427,
 0.029230985790491104,
 0.020046386867761612,
 0.023800091817975044,
 -0.04696125537157059,
 -0.0067886169999837875,
 0.0032345762010663748,
 -0.014375894330441952,
 -0.05878143385052681,
 -0.03258536010980606,
 0.014615492895245552,
 0.0268350038677454,
 0.039933040738105774,
 0.03817598521709442,
 -0.005670491605997086,
 -0.028112860396504402,
 -0.028112860396504402,
 -0.0062295543029904366,
 0.034981343895196915,
 0.012698707170784473,
 -0.07922714948654175,
 -0.024598753079771996,
 0.06485125422477722,
 -0.041530363261699677,
 -0.017810136079788208,
 0.034821610897779465,
 -0.06932375580072403,
 0.034661877900362015,
 0.007108081132173538,
 -0.020285984501242638,
 -0.005351027473807335,
 -0.014216162264347076,
 -0.0024059657007455826,
 0.05878143385052681,
 0.03258536010980606,
 0.016372546553611755,
 -0.012778572738170624,
 -0.01892826147377491,
 -0.028112860396504402,
 -0.006509085651487112,
 -0.04216929152607918,
 -0.013657099567353725,
 0.012618840672075748,
 0.012618840672075748,
 0.023161163553595543,
 -0.045363932847976685,
 0.02108464576303959,
 -0.045363932847976685,
 0.019647056236863136,
 0.012698707170784473,
 0.012698707170784473,
 0.05015590041875839,
 -0.06772643327713013,
 -0.028751788660883904,
 -0.023001430556178093,
 -0.0012329326709732413,
 -0.003893471322953701,
 0.06389286369085312,
 0.02124437689781189,
 -0.03737732395529747,
 -0.008505737408995628,
 0.012538975104689598,
 0.008066474460065365,
 0.030189378187060356,
 -0.02651553973555565,
 0.03801625594496727,
 -0.035300806164741516,
 -0.04887804016470909,
 0.03817598521709442,
 0.04121089726686478,
 0.00551075953990221,
 -0.035780005156993866,
 -0.02140410989522934,
 0.02220277115702629,
 -0.014855091460049152,
 -0.0069084158167243,
 0.018369197845458984,
 -0.0019167859572917223,
 0.001128108357079327,
 -0.012618840672075748,
 -0.06804589927196503,
 0.022681966423988342,
 0.007667143829166889,
 0.030349111184477806,
 0.0134175019338727,
 -0.012459108605980873,
 0.008146340027451515,
 -0.0134175019338727,
 -0.009504063986241817,
 0.051114290952682495,
 -0.016931608319282532,
 0.029230985790491104,
 0.03737732395529747,
 -0.024758484214544296,
 -0.07283786684274673,
 -0.0075872777961194515,
 0.024598753079771996,
 -0.026036342605948448,
 0.06644857674837112,
 0.011340983211994171,
 0.00102827581577003,
 -0.024279288947582245,
 0.009224532172083855,
 -0.0035740071907639503,
 -0.02779339626431465,
 -0.015733618289232254,
 0.002026601694524288,
 -0.011660447344183922,
 0.03402294963598251,
 0.03434241563081741,
 0.011900045908987522,
 -0.04472500458359718,
 -0.005151362158358097,
 0.03402294963598251,
 0.017969869077205658,
 -0.02619607374072075,
 0.04376661404967308,
 0.0022162836976349354,
 -0.0032345762010663748,
 0.0008685436332598329,
 -0.0134175019338727,
 -0.040731701999902725,
 -0.017410805448889732,
 0.06261500716209412,
 -0.009743661619722843,
 -0.014216162264347076,
 0.029869914054870605,
 -0.00345420790836215,
 -0.004312768578529358,
 0.034821610897779465,
 0.023800091817975044,
 0.008785269223153591,
 0.014535626396536827,
 -0.011101385578513145,
 0.03354375436902046,
 0.01956718973815441,
 0.016372546553611755,
 -0.003953371196985245,
 -0.013098036870360374,
 0.0010332674719393253,
 -0.015494019724428654,
 0.01046245638281107,
 0.011500715278089046,
 0.06293447315692902,
 -0.052072685211896896,
 -0.04376661404967308,
 -0.03242562711238861,
 -0.008625537157058716,
 0.011900045908987522,
 0.06325393915176392,
 -0.0546283982694149,
 -0.02204303815960884,
 -0.0015374220674857497,
 -0.004911764059215784,
 -0.012219510041177273,
 -0.02651553973555565,
 0.005071496125310659,
 -0.04472500458359718,
 -0.006109755020588636,
 0.030189378187060356,
 0.00044425507076084614,
 -0.00539096025750041,
 0.009424197487533092,
 0.01812960021197796,
 0.061017684638500214,
 -0.014615492895245552,
 0.0072678131982684135,
 -0.03801625594496727,
 -0.07219893485307693,
 -0.0035141075495630503,
 0.006389286369085312,
 0.04919750615954399,
 -0.006309420336037874,
 0.006988281849771738,
 -0.04791964963078499,
 -0.018848394975066185,
 0.005031562875956297,
 -0.0276336632668972,
 -0.01126111764460802,
 -0.07347679138183594,
 0.0276336632668972,
 0.03881491348147392,
 0.005670491605997086,
 0.015254421159625053,
 0.008186273276805878,
 0.02188330702483654,
 -0.024918217211961746,
 -0.029710182920098305,
 -0.035300806164741516,
 -0.04887804016470909,
 0.02619607374072075,
 -0.028911521658301353,
 0.023959824815392494,
 -0.03929411247372627,
 0.025237681344151497,
 0.003713772865012288,
 -0.051114290952682495,
 0.012858439236879349,
 0.003913437947630882,
 0.0029750114772468805,
 0.03434241563081741,
 0.0543089359998703,
 0.02715446799993515,
 0.008385938592255116,
 -0.0004242885624989867,
 -0.04472500458359718,
 0.004931730683892965,
 -0.015573885291814804,
 -0.00411310326308012,
 -0.035300806164741516,
 0.045683398842811584,
 -0.009144666604697704,
 0.07283786684274673,
 0.012618840672075748,
 0.024119555950164795,
 0.01597321592271328,
 -0.03450214862823486,
 0.0015773550840094686,
 -0.01860879734158516,
 -0.02252223528921604,
 0.028751788660883904,
 -0.03146723657846451,
 -0.0523921474814415,
 -0.06708750873804092,
 -0.03290482610464096,
 -0.05782304331660271,
 -0.008825201541185379,
 -0.0527116134762764,
 0.018688661977648735,
 -0.0546283982694149,
 -0.03370348736643791,
 -0.01629268005490303,
 0.017650403082370758,
 0.03290482610464096,
 -0.013018171302974224,
 -0.07379625737667084,
 0.005430893506854773,
 0.03306455910205841,
 0.055906254798173904,
 0.0268350038677454,
 -0.01924772560596466,
 0.041530363261699677,
 0.030029647052288055,
 -0.024758484214544296,
 -0.023161163553595543,
 -0.04248875379562378,
 0.050475362688302994,
 -0.02252223528921604,
 0.0075872777961194515,
 0.029230985790491104,
 0.04504447057843208,
 0.0035141075495630503,
 0.0062295543029904366,
 -0.034661877900362015,
 -0.01597321592271328,
 0.03753705695271492,
 -0.020365850999951363,
 -0.003853538306429982,
 0.04760018363595009,
 0.08306072652339935,
 -0.06549018621444702,
 -0.013657099567353725,
 0.061656612902879715,
 -0.00411310326308012,
 0.0038335719145834446,
 -0.02140410989522934,
 -0.005311094224452972,
 0.011580581776797771,
 0.006189621053636074,
 0.010063125751912594,
 -0.029071252793073654,
 0.03897464647889137,
 -0.019327592104673386,
 -0.029390716925263405,
 -0.009464130736887455,
 -0.030189378187060356,
 -0.0070282150991261005,
 -0.01581348478794098,
 -0.005231228191405535,
 -0.07124054431915283,
 0.004752031993120909,
 0.011979912407696247,
 0.04760018363595009,
 -0.04951696842908859,
 0.04728072136640549,
 0.02172357402741909,
 -0.03258536010980606,
 0.03881491348147392,
 -0.07411572337150574,
 0.016532279551029205,
 0.0035340741742402315,
 -0.05846197158098221,
 -0.02108464576303959,
 -0.0555867925286293,
 0.009504063986241817,
 0.008905068039894104,
 0.030349111184477806,
 0.009943326935172081,
 -0.016931608319282532,
 -0.01876852847635746,
 -0.04664178937673569,
 0.07124054431915283,
 0.023640360683202744,
 0.02108464576303959,
 -0.01677187718451023,
 0.009424197487533092,
 0.018369197845458984,
 -0.029550449922680855,
 -0.07858822494745255,
 -0.012538975104689598,
 -0.014535626396536827,
 -0.024279288947582245,
 0.014615492895245552,
 0.005790290888398886,
 0.017810136079788208,
 0.0005790290888398886,
 0.010222858749330044,
 -0.01677187718451023,
 -0.005910090170800686,
 -0.024119555950164795,
 0.034661877900362015,
 -0.041530363261699677,
 -0.019487323239445686,
 -0.02124437689781189,
 0.030508842319250107,
 -0.045683398842811584,
 -0.001597321592271328,
 0.017330938950181007,
 -0.023959824815392494,
 0.020445717498660088,
 0.007507411763072014,
 0.02236250229179859,
 0.045363932847976685,
 0.06069822236895561,
 0.0543089359998703,
 -0.03705786168575287,
 -0.03817598521709442,
 0.06037875637412071,
 -0.08242179453372955,
 0.023161163553595543,
 0.11181250959634781,
 0.014695358462631702,
 -0.03130750358104706,
 0.0018169532995671034,
 -0.09264465421438217,
 0.040731701999902725,
 -0.009344330988824368,
 0.029710182920098305,
 -0.001427606213837862,
 -0.08561643958091736,
 -0.05782304331660271,
 0.050794828683137894,
 0.024918217211961746,
 -0.03801625594496727,
 0.0274739321321249,
 -0.010542322881519794,
 0.03625920042395592,
 0.024279288947582245,
 0.014136296696960926,
 -0.03146723657846451,
 -0.04664178937673569,
 0.05015590041875839,

In [44]:
len(embedding)

1024

In [49]:
def get_embedding(text, model = 'voyage-3'):
        result = vo.embed(
                [text],
                model=model,
                input_type="document"
        )
        return result.embeddings[0]

In [55]:
print(get_embedding("hi"))
len(get_embedding("hi")) #1024

[-0.015087280422449112, -0.031107794493436813, -0.043239835649728775, 0.008204680867493153, 0.002459459938108921, 0.05350540578365326, 0.0055994028225541115, -0.016331592574715614, -0.003266318468376994, 0.054127562791109085, 0.01889798603951931, -0.012754195369780064, -0.018586907535791397, -0.004763381090015173, -0.010965497232973576, 0.0012054269900545478, -0.006843714974820614, 0.051016781479120255, 0.06968145817518234, 0.00937122292816639, -0.020220065489411354, 0.02084222249686718, -0.004938362166285515, 0.003363530384376645, -0.06688176095485687, 0.01143211405724287, 0.0396624393761158, 0.006338213104754686, -0.0018956311978399754, 0.006415982730686665, -0.030330099165439606, -0.0650152936577797, -0.01882021501660347, -0.02286422811448574, -0.021308839321136475, 0.028463631868362427, 0.0035190691705793142, -0.03639611974358559, -0.0009332338231615722, -0.04852816089987755, 0.001817861688323319, -0.01796475052833557, -0.06563744693994522, 0.016720440238714218, -0.05630510672926903, 0.020686684176325798, 0.008282450027763844, -0.008165796287357807, -0.044173069298267365, -0.025197314098477364, -0.01586497575044632, 0.003732935292646289, -0.00766029441729188, -0.015553897246718407, -0.020220065489411354, 0.018353598192334175, 0.02193099446594715, -0.031107794493436813, -0.0497724711894989, -0.007193677593022585, -0.023175306618213654, 0.023486385121941566, 0.007621409837156534, 0.0035190691705793142, -0.04044013097882271, -0.019442372024059296, 0.03686273470520973, -0.0018956311978399754, -0.013065273873507977, -0.02893024869263172, 0.020375605672597885, -0.002741374308243394, -0.02270868979394436, 0.03701827675104141, -0.019209062680602074, -0.01438735518604517, -0.020375605672597885, -0.02566393092274666, -0.012754195369780064, -0.022553151473402977, -0.016331592574715614, -0.004335648845881224, 0.004102340433746576, -0.0472838468849659, -0.018431367352604866, 0.00886572152376175, -0.020531143993139267, -0.015165049582719803, 0.02581946924328804, 0.04075121134519577, -0.02301976829767227, -0.024108540266752243, -0.010343342088162899, 0.038262587040662766, 0.04044013097882271, -0.0047439387999475, -0.025975007563829422, -0.0307967159897089, 0.05723834037780762, 0.015242819674313068, -0.008515758439898491, -0.0160205140709877, 0.059104807674884796, -0.011043267324566841, 0.029552403837442398, 0.010343342088162899, 0.045106302946805954, -0.06625960022211075, 0.02084222249686718, 0.01290973462164402, 0.005093901418149471, 0.02395300194621086, 0.02301976829767227, 0.004763381090015173, 0.0168759785592556, -0.017109286040067673, 0.07839164137840271, -0.004802265670150518, -0.0497724711894989, 0.060971278697252274, 0.010576650500297546, -0.0036940504796802998, 0.028463631868362427, -0.02861917018890381, -0.01679820939898491, 0.009682301431894302, 0.020375605672597885, -0.03452965244650841, -0.0615934319794178, -0.01345412153750658, -0.0029552404303103685, -0.019286831840872765, 0.038262587040662766, -0.03515180945396423, 0.044173069298267365, 0.03064117766916752, -0.013609659858047962, 0.03359641879796982, 0.004238436929881573, -0.00024424478760920465, 0.01882021501660347, -0.00645486731082201, -0.023486385121941566, -0.019364602863788605, -0.01874244585633278, 0.021619917824864388, -0.009332338348031044, -0.007271446753293276, -0.026130547747015953, 0.032352104783058167, 0.04075121134519577, 0.002935798140242696, 0.007349216379225254, 0.005793826654553413, 0.011587653309106827, -0.03904028236865997, -0.012598657049238682, -0.018431367352604866, -0.011043267324566841, -0.01197650097310543, 0.033440880477428436, 0.012598657049238682, 0.04946139454841614, -0.03452965244650841, 0.004393976181745529, -0.053194329142570496, -0.006027135066688061, 0.07559194415807724, -0.013920738361775875, -0.0050550163723528385, 0.034374114125967026, 0.04261767864227295, 0.0015456685796380043, -0.02193099446594715, -0.03841812536120415, 0.033129800111055374, 0.014698432758450508, -0.03484072908759117, 0.037173815071582794, 0.007543640211224556, 0.005910480860620737, -0.008282450027763844, -0.04292875528335571, 0.026130547747015953, -0.021153301000595093, 0.012754195369780064, 0.024419618770480156, 0.0023428057320415974, 0.021619917824864388, 0.04852816089987755, -0.0012345905415713787, -0.01780921220779419, 0.00036454445216804743, 0.05972696468234062, -0.038107048720121384, 0.027997015044093132, -0.010654419660568237, -0.04168444499373436, 0.0018081405432894826, -0.008593528531491756, 0.008321334607899189, 0.01438735518604517, -0.012754195369780064, 0.005443864036351442, -0.030330099165439606, -0.019131293520331383, 0.017575904726982117, -0.06625960022211075, 0.016642669215798378, -0.028463631868362427, 0.004316206555813551, -0.006338213104754686, -0.005988250486552715, 0.020220065489411354, -0.027219319716095924, 0.01990898884832859, 0.0615934319794178, -0.011665422469377518, 0.06283774226903915, -0.04044013097882271, -0.027219319716095924, -0.035307347774505615, 0.02084222249686718, -0.04199552163481712, 0.01967567950487137, -0.028463631868362427, -0.0020803336519747972, 0.002819143934175372, 0.009760070592164993, 0.017109286040067673, 0.012209809385240078, 0.04044013097882271, -0.05039462819695473, -0.001953958300873637, 0.020064527168869972, -0.007893603295087814, -0.01990898884832859, 0.05163893848657608, -0.04448414593935013, 0.043239835649728775, -0.10514434427022934, 0.011276575736701488, 0.017420364543795586, -0.03841812536120415, -0.027219319716095924, -0.018586907535791397, -0.002488623606041074, 0.03250764682888985, -0.03670719638466835, 0.02566393092274666, 0.02566393092274666, -0.051016781479120255, 0.005210555624216795, -0.009137914516031742, 0.031107794493436813, -0.00991560984402895, 0.03888474404811859, -0.0307967159897089, -0.05381648615002632, 0.07061469554901123, 0.036240581423044205, -0.030019022524356842, 0.034218572080135345, -0.014776201918721199, 0.03592950105667114, -0.01384296827018261, 0.004413418471813202, -0.04603953659534454, -0.02099776081740856, 0.03390749543905258, 0.07776948809623718, -0.025197314098477364, 0.030330099165439606, 0.034063033759593964, 0.006027135066688061, -0.04199552163481712, -0.00025032053235918283, 0.0046078418381512165, 0.02286422811448574, -0.026597164571285248, -0.021308839321136475, 0.03888474404811859, -0.003227433655411005, 0.02986348234117031, -0.009721186012029648, -0.059104807674884796, -0.01197650097310543, 0.027219319716095924, 0.0034607420675456524, -0.01539835799485445, 0.004141225013881922, -0.020531143993139267, -0.007776948623359203, 0.033285338431596756, 0.06314882636070251, -0.029552403837442398, -0.02177545614540577, 0.0029163556173443794, -0.009410107508301735, -0.021308839321136475, -0.014698432758450508, -0.022086534649133682, 0.018120290711522102, 0.04199552163481712, -0.013298582285642624, 0.011587653309106827, -0.07061469554901123, 0.05350540578365326, 0.0013804084155708551, -0.02986348234117031, 0.004141225013881922, -0.01975344866514206, 0.005288325250148773, 0.013531890697777271, 0.02301976829767227, -0.04168444499373436, 0.02488623559474945, 0.028308093547821045, -0.03686273470520973, -0.03188548982143402, -0.011587653309106827, 0.004685611464083195, 0.03701827675104141, -0.01874244585633278, 0.03686273470520973, 0.0675039142370224, 0.012054270133376122, 0.013376351445913315, -0.09021260589361191, 0.03655165806412697, -0.0160205140709877, 0.03686273470520973, 0.018275829032063484, -0.025508390739560127, 0.016409361734986305, -0.0075047556310892105, -0.006921484135091305, -0.008476873859763145, 0.037329353392124176, 0.014776201918721199, 0.0047050537541508675, -0.008710182271897793, -0.023486385121941566, -0.04852816089987755, 0.0022455938160419464, -0.026597164571285248, -0.02768593654036522, -0.002265036338940263, -0.02861917018890381, 0.0017206498887389898, 0.010654419660568237, -0.030019022524356842, -0.05817157402634621, -0.026441624388098717, -0.012598657049238682, 0.03452965244650841, 0.07403655350208282, -0.016176052391529083, -0.0013901295606046915, -0.006610406097024679, 0.051016781479120255, -0.03484072908759117, 0.015165049582719803, 0.036240581423044205, -0.06439313292503357, -0.06345990300178528, 0.06439313292503357, 0.000544386391993612, 0.015165049582719803, -0.033285338431596756, 0.08710182458162308, 0.06066019833087921, -0.05537187308073044, -0.01695374771952629, 0.03157441318035126, -0.026130547747015953, -0.008399104699492455, 0.04946139454841614, -0.006182674318552017, 0.01586497575044632, 0.09892278909683228, 0.024419618770480156, 0.01990898884832859, 0.025975007563829422, -0.017653673887252808, -0.0070381383411586285, -0.00987672433257103, -0.04479522258043289, -0.021153301000595093, 0.0307967159897089, -0.025197314098477364, -0.024575157091021538, 0.021464377641677856, 0.010343342088162899, -0.04199552163481712, 0.03172995150089264, -0.022397611290216446, 0.041062287986278534, 0.040129054337739944, -0.025197314098477364, -0.017187057062983513, 0.016253823414444923, -0.015631666406989098, -0.034218572080135345, 0.030019022524356842, -0.006415982730686665, -0.005638287868350744, -0.004685611464083195, 0.027063781395554543, 0.017420364543795586, -0.02099776081740856, -0.030330099165439606, -0.0010401668259873986, 0.01384296827018261, 0.03639611974358559, 0.017653673887252808, -0.042306602001190186, 0.02395300194621086, 0.03499626740813255, -0.005560518242418766, -0.0320410281419754, 0.013687429949641228, -0.02286422811448574, 0.03748489171266556, 0.04883923754096031, 0.00937122292816639, -0.010887728072702885, -0.010887728072702885, 0.06314882636070251, 0.07154792547225952, -0.015087280422449112, 0.017264826223254204, -0.008243565447628498, 0.07621409744024277, 0.06594852358102798, -0.011665422469377518, -0.05070570483803749, 0.018586907535791397, -0.01897575519979, -0.01570943556725979, -0.0069603691808879375, 0.029241327196359634, -0.027374859899282455, -0.017031516879796982, 0.012598657049238682, 0.01990898884832859, -0.05786049738526344, 0.003616281086578965, 0.012520886957645416, -0.027530398219823837, -0.031263332813978195, -0.023486385121941566, -0.02193099446594715, -0.030330099165439606, 0.014776201918721199, 0.03872920572757721, 0.04479522258043289, -8.749066910240799e-05, 0.002721932018175721, -0.017498133704066277, 0.008399104699492455, -0.0013220813125371933, 0.00801025703549385, -0.04479522258043289, -0.03390749543905258, 0.0030718946363776922, 0.035462886095047, 0.0047244965098798275, 0.0006367376772686839, -0.008593528531491756, 0.014154046773910522, -0.041062287986278534, -0.0008506037411279976, -0.01384296827018261, -0.04199552163481712, 0.016409361734986305, 0.0050550163723528385, 0.013143043033778667, 0.027997015044093132, 0.019131293520331383, 0.01135434489697218, -0.03141887113451958, 0.013998507522046566, 0.025352852419018745, 0.02986348234117031, -0.008515758439898491, 0.041062287986278534, 0.03064117766916752, 0.014620663598179817, -0.024419618770480156, 0.0046272845938801765, 0.019520141184329987, -0.004121782723814249, -0.0018664676463231444, 0.06688176095485687, -0.0055216336622834206, -0.028152553364634514, -0.011665422469377518, 0.032352104783058167, -0.070925772190094, 0.05132786184549332, 0.08025810867547989, -0.001215148251503706, -0.0025469507090747356, 0.0438619889318943, -0.032196566462516785, 0.005988250486552715, -0.018120290711522102, 0.0005370955332182348, -0.015631666406989098, -0.003130221739411354, 0.0055216336622834206, 0.028152553364634514, -0.016409361734986305, 0.02286422811448574, 0.0007485313108190894, -0.017653673887252808, -0.008593528531491756, -0.006377097684890032, 0.014542893506586552, 0.010032263584434986, -0.017653673887252808, -0.019131293520331383, 0.020220065489411354, -0.027219319716095924, -0.036240581423044205, 0.034374114125967026, -0.02690824307501316, -0.004549514967948198, 0.01882021501660347, -0.0061437892727553844, -0.0852353572845459, -0.006571521516889334, -0.03266318514943123, -0.021308839321136475, 0.03841812536120415, -0.027374859899282455, 0.05661618709564209, -0.051016781479120255, -0.013376351445913315, 0.009565646760165691, -0.02286422811448574, 0.0025858355220407248, 0.028463631868362427, 0.026286086067557335, 0.007154792547225952, -0.03188548982143402, 0.025352852419018745, -0.027063781395554543, 0.009526762180030346, 0.017109286040067673, -0.0024497387930750847, -0.010654419660568237, -0.06128235533833504, 0.0084379892796278, -0.027063781395554543, 0.014231815934181213, 0.0032079913653433323, 0.015553897246718407, -0.023486385121941566, -0.024108540266752243, -0.013220812194049358, -0.015009511262178421, -0.01594274491071701, 0.05039462819695473, 0.014154046773910522, 0.03390749543905258, -0.05443863943219185, -0.04759492725133896, 0.03499626740813255, -0.016176052391529083, -0.03748489171266556, 0.011665422469377518, -0.024264080449938774, -0.008049141615629196, -0.026597164571285248, -0.024264080449938774, -0.010887728072702885, 0.006999253761023283, -0.004102340433746576, 0.0396624393761158, -0.0675039142370224, 0.041373368352651596, 0.013220812194049358, -0.02193099446594715, -0.018509138375520706, 0.003188548842445016, -0.01594274491071701, -0.04697277024388313, -0.01990898884832859, 0.04852816089987755, -0.04261767864227295, 0.03592950105667114, 0.001788698136806488, -0.009254569187760353, -0.06221558898687363, -0.01796475052833557, -0.009565646760165691, -0.020686684176325798, -0.037173815071582794, 0.000957536802161485, 0.01874244585633278, -0.025197314098477364, -0.023330844938755035, -2.2176454876898788e-05, -0.00987672433257103, 0.0033440878614783287, -0.02690824307501316, 0.0041801100596785545, 0.021464377641677856, 0.015087280422449112, -0.012676426209509373, -0.02084222249686718, -0.02861917018890381, 0.03764043003320694, 0.04044013097882271, -0.05972696468234062, 0.014231815934181213, 0.02364192344248295, 0.017187057062983513, 0.02177545614540577, -0.009837839752435684, -0.0020803336519747972, -0.005443864036351442, 0.037173815071582794, -0.030174560844898224, -0.016331592574715614, 0.06470420956611633, -0.024419618770480156, -0.01446512434631586, 0.022242072969675064, -0.029241327196359634, -0.005871596280485392, -0.017109286040067673, 0.001341523602604866, 0.02473069727420807, 0.0070381383411586285, 0.01990898884832859, -0.010187802836298943, 0.03670719638466835, -0.037173815071582794, -0.01874244585633278, -0.03795151039958, 0.0160205140709877, 0.03468519076704979, -0.03670719638466835, -0.03157441318035126, -0.03577396273612976, -0.006804829929023981, 0.02301976829767227, 0.08336888998746872, -0.03904028236865997, 0.0017012074822559953, -0.03592950105667114, -0.01446512434631586, 0.005832711234688759, -0.008204680867493153, 0.008515758439898491, -0.031263332813978195, -0.021464377641677856, 0.030174560844898224, -0.025975007563829422, -0.04448414593935013, -0.019131293520331383, -0.034063033759593964, 0.042306602001190186, -0.03561842441558838, -0.019053524360060692, -0.06905930489301682, -0.04603953659534454, 0.025197314098477364, -0.0046272845938801765, 0.05132786184549332, 0.01679820939898491, -0.006571521516889334, -0.08585751056671143, 0.016487130895256996, -0.04355091229081154, -0.018353598192334175, 0.009954494424164295, -0.01882021501660347, 6.652936281170696e-05, 0.06937038153409958, -0.003869032021611929, 0.04946139454841614, 0.017575904726982117, 0.029241327196359634, -0.015553897246718407, -0.024264080449938774, -0.01570943556725979, -0.009021260775625706, 0.007699178997427225, -0.04697277024388313, 0.024264080449938774, 0.003635723376646638, 0.06625960022211075, 0.015242819674313068, 0.01532058883458376, 0.014542893506586552, -0.026286086067557335, -0.02395300194621086, 0.049150314182043076, 0.04759492725133896, 0.04199552163481712, 0.01438735518604517, 0.009643415920436382, -0.003771820105612278, 0.03592950105667114, 0.019442372024059296, -0.07185900211334229, 0.018586907535791397, 0.02893024869263172, 0.01889798603951931, 0.07652517408132553, 0.012987503781914711, 0.006571521516889334, 0.05381648615002632, -0.017109286040067673, -0.017498133704066277, 0.017109286040067673, -0.019364602863788605, 0.027374859899282455, -0.03359641879796982, 0.017653673887252808, -0.02970794402062893, -0.04261767864227295, -0.06377097964286804, -0.01532058883458376, -0.05754942074418068, 0.004102340433746576, -0.03639611974358559, -0.008982375264167786, -0.021464377641677856, 0.070925772190094, 0.03764043003320694, -0.017031516879796982, -0.060038045048713684, -0.03064117766916752, 0.014309585094451904, 0.05848265439271927, 0.04635061323642731, -0.03157441318035126, -0.004568957258015871, 0.019131293520331383, -0.004335648845881224, -0.03172995150089264, -0.023330844938755035, 0.02488623559474945, -0.005793826654553413, 0.030174560844898224, 0.002459459938108921, 0.06905930489301682, -0.02986348234117031, 0.023175306618213654, -0.029552403837442398, -0.014931741170585155, 0.05039462819695473, -0.004393976181745529, 0.011198805645108223, 0.0055994028225541115, 0.07217008620500565, -0.025197314098477364, 0.02099776081740856, 0.028463631868362427, 0.0016234379727393389, 0.019209062680602074, -0.004432860761880875, 0.03172995150089264, 0.0055994028225541115, 0.006299328524619341, 0.03888474404811859, 0.007582524791359901, 0.035462886095047, -0.014309585094451904, 0.0008749067201279104, -0.031107794493436813, -0.026130547747015953, 0.02193099446594715, -0.014776201918721199, 0.012132040224969387, -0.05443863943219185, -0.006221558898687363, 0.028463631868362427, -0.003927358891814947, -0.0497724711894989, 0.029241327196359634, -0.010265571996569633, -0.035462886095047, 0.056927263736724854, -0.028463631868362427, 0.0026052778121083975, -0.027063781395554543, -0.015009511262178421, 0.009721186012029648, -0.03904028236865997, 0.004491187632083893, 0.025041773915290833, 0.04759492725133896, -0.02270868979394436, -0.014076276682317257, -0.013531890697777271, -0.03561842441558838, 0.07248116284608841, -0.021153301000595093, -0.015165049582719803, 0.023175306618213654, 0.002177545567974448, 0.023175306618213654, -0.015009511262178421, -0.07465870678424835, 0.027530398219823837, -0.02301976829767227, -0.07528086006641388, 0.015009511262178421, -0.00223587267100811, -0.021619917824864388, -0.0320410281419754, -0.007349216379225254, 0.014076276682317257, 0.023330844938755035, -0.009137914516031742, 0.0615934319794178, -0.02488623559474945, 0.0028969133272767067, -0.038262587040662766, 0.035462886095047, -0.08274673670530319, -0.01532058883458376, 0.004646726883947849, 0.009099029935896397, 0.014853972010314465, 0.05474971979856491, 0.01049888040870428, -0.0018956311978399754, 0.07590302079916, -0.01135434489697218, 0.007154792547225952, -0.029552403837442398, 0.03359641879796982, -0.10390003025531769, -0.0027024897281080484, 0.11634314805269241, 0.005871596280485392, 0.000510362267959863, 0.020686684176325798, -0.05723834037780762, 0.0055994028225541115, -0.005638287868350744, 0.08025810867547989, 0.010110032744705677, -0.03795151039958, -0.06345990300178528, 0.010887728072702885, -0.010187802836298943, -0.014853972010314465, 0.021308839321136475, -0.015087280422449112, 0.023486385121941566, 0.008593528531491756, 0.030174560844898224, -0.024419618770480156, -0.030330099165439606, 0.08336888998746872, 0.006804829929023981, -0.011043267324566841, -0.022553151473402977, -0.0472838468849659, -0.007349216379225254, -0.0025663929991424084, -0.004646726883947849, 0.03981797769665718, 0.018120290711522102, 0.018586907535791397, 0.02893024869263172, 0.04199552163481712, -0.005210555624216795, 0.03686273470520973, 0.009215683676302433, 0.044173069298267365, -0.051950015127658844, 0.013998507522046566, 0.01345412153750658, 0.004024570807814598, -0.0009380944538861513, -0.03795151039958, 0.00031836883863434196, -0.016176052391529083, -0.0050550163723528385, 0.05132786184549332, 0.020686684176325798, 0.011276575736701488, -0.01135434489697218, -0.019131293520331383, 0.03935135900974274, -0.028152553364634514, -0.01438735518604517, 0.005793826654553413, -0.003421857487410307, 0.055994030088186264, 0.03172995150089264, -0.009021260775625706, -0.007543640211224556, -0

1024

# Create qdrant collection

In [56]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

qdrant_client = QdrantClient(url = "http://localhost:6333")

# size is the size of vector from the embeding
qdrant_client.create_collection(
        collection_name="Amazon-items-collection-00",
        vectors_config=VectorParams(size=1024, distance=Distance.COSINE)
)

True

### Embed Data

In [57]:
# test
pointstruct = PointStruct(
        id = 0,
        vector = get_embedding("Test text"),
        payload={
                "text": "Test text",
                "model": "voyage-3",
        },
)
pointstruct

PointStruct(id=0, vector=[-0.0195973701775074, -0.04089885950088501, 0.015337072312831879, -0.003098398447036743, 0.02881510555744171, 0.019519910216331482, 0.03547666221857071, -0.021533869206905365, -1.4523742720484734e-05, 0.06196796894073486, -0.0005397991044446826, -0.013555493205785751, -0.05081373453140259, -0.013013273477554321, -0.023083068430423737, 0.014407552778720856, -0.008636785671114922, 0.02509702742099762, 0.03547666221857071, 0.026956066489219666, -0.011541534215211868, 0.02773066610097885, -0.01859039068222046, -0.006235526874661446, -0.050503894686698914, 0.04306773841381073, 0.020449429750442505, -0.012625973671674728, -0.01742849126458168, 0.001195788150653243, -0.05174325406551361, -0.07622060179710388, -0.02230846881866455, -0.024787187576293945, -0.010302174836397171, 0.021069109439849854, 0.0013458668254315853, -0.005925687029957771, -0.0063517168164253235, -0.03144874423742294, -0.011696454137563705, -0.040589019656181335, -0.03532174229621887, 0.0458562970161438, -0.018358010798692703, 0.013942793011665344, 0.009992334991693497, 0.012471053749322891, -0.009217735379934311, -0.03175858408212662, -0.020294509828090668, -0.004957437515258789, -0.017118651419878006, 0.028505265712738037, -0.021378949284553528, 0.009527575224637985, -0.03392746299505234, 0.015337072312831879, -0.02075926959514618, -0.04616613686084747, -0.02230846881866455, 0.019829750061035156, 0.03965950012207031, 0.002081736456602812, -0.006274256855249405, -0.019984669983386993, 0.02897002547979355, 0.006429176777601242, 0.005034897476434708, -0.031293824315071106, 0.024167507886886597, 0.03780046105384827, 0.03423730283975601, 0.005112357437610626, 0.0097986850887537, 0.013478033244609833, -0.06816476583480835, -0.016498971730470657, -0.0283503457903862, 0.03718078136444092, 0.011386614292860031, 0.049264535307884216, -0.0162665918469429, -0.026491306722164154, -0.019829750061035156, 0.0005349578568711877, -0.04089885950088501, 0.02726590633392334, 0.010457094758749008, 0.019210070371627808, -0.05979909002780914, -0.023857668042182922, 0.005925687029957771, 0.014639932662248611, 0.009217735379934311, 0.008288215845823288, -0.019210070371627808, -0.01200629398226738, 0.05824989080429077, 0.01859039068222046, -0.01092185452580452, -0.029589705169200897, 0.028195425868034363, -0.0011570581700652838, 0.02401258796453476, -0.03996933996677399, 0.028195425868034363, -0.08117803931236267, 0.008365675806999207, -0.010302174836397171, -0.028195425868034363, 0.008636785671114922, 0.006429176777601242, -0.01363295316696167, -0.02401258796453476, -0.04833501577377319, 0.01905515044927597, -0.03780046105384827, -0.028505265712738037, 0.04399725794792175, -0.0056933071464300156, -0.006235526874661446, 0.06041876971721649, 0.001258724369108677, 0.027575746178627014, 0.022618308663368225, 0.024167507886886597, 0.02447734773159027, -0.06816476583480835, 0.014562472701072693, -0.02881510555744171, -0.010766934603452682, 0.0325331836938858, -0.03872998058795929, -0.0005228547379374504, 0.0350119024515152, 0.013710413128137589, 0.04182837903499603, 0.0026917336508631706, -0.013787873089313507, -0.022153548896312714, -0.006429176777601242, -0.018435470759868622, -0.0006245209369808435, -0.0011038044467568398, 0.013168193399906158, -0.013865333050489426, -0.0027110986411571503, 0.0037374431267380714, -0.01742849126458168, -0.01905515044927597, -0.06413684785366058, 0.0015976116992533207, -0.011851374059915543, 0.010766934603452682, -0.05112357437610626, 0.012703433632850647, -0.008365675806999207, 0.01254851371049881, 0.006700286641716957, 0.03268810361623764, 0.023857668042182922, 0.026956066489219666, 0.007397426292300224, 0.03718078136444092, -0.06041876971721649, 0.0013845968060195446, 0.031913504004478455, -0.004570137709379196, -0.021069109439849854, 0.04306773841381073, 0.054841652512550354, 0.019519910216331482, -0.019829750061035156, -0.0051510874181985855, 0.050503894686698914, 0.007203776389360428, -0.010224714875221252, 0.027110986411571503, 0.027420826256275177, 0.06413684785366058, -0.016189131885766983, -0.027420826256275177, 0.006816476583480835, -0.010224714875221252, -0.012703433632850647, 0.0141751728951931, -0.05886957049369812, 0.023547828197479248, 0.018745310604572296, 0.03888490051031113, -0.016034211963415146, 0.0025755437090992928, 0.0283503457903862, -0.05298261344432831, -0.012780893594026566, -0.04399725794792175, -0.042757898569107056, -0.024167507886886597, 0.010224714875221252, 0.041208699345588684, 0.04213821887969971, 0.03857506066560745, -0.01525961235165596, -0.006390446797013283, -0.041208699345588684, 0.01735103130340576, -0.04523661732673645, 0.009759955108165741, -0.03284302353858948, 0.018822770565748215, -0.013865333050489426, 0.010224714875221252, 0.0446169376373291, 0.003911728039383888, 0.01309073343873024, 0.033462703227996826, -0.01471739262342453, 0.03268810361623764, 0.014485012739896774, -0.018822770565748215, -0.03175858408212662, 0.0337725430727005, -0.03160366415977478, -0.007126316428184509, -0.013168193399906158, -0.0032533183693885803, 0.005577117204666138, 0.024167507886886597, 0.0034082382917404175, 0.014020252972841263, -0.0097986850887537, -0.05360229313373566, -0.015956752002239227, 0.01363295316696167, -0.003098398447036743, -0.03423730283975601, 0.029279865324497223, -0.05019405484199524, 0.0175059512257576, -0.06723524630069733, -0.015027232468128204, 0.017893251031637192, -0.012625973671674728, -0.011386614292860031, -0.021998628973960876, -0.007436156272888184, -0.005770767107605934, -0.018358010798692703, 0.012935813516378403, 0.03098398447036743, 0.07126316428184509, -0.020449429750442505, -0.030674144625663757, 0.028660185635089874, 0.015182152390480042, 0.02184370905160904, -0.017583411186933517, 0.0006777746602892876, 0.07436156272888184, 0.024167507886886597, -0.03996933996677399, 0.018667850643396378, -0.03857506066560745, 0.009992334991693497, 0.007397426292300224, -0.008288215845823288, -0.04430709779262543, -0.04647597670555115, -0.021688789129257202, 0.005577117204666138, -0.041208699345588684, 0.03485698252916336, 0.009527575224637985, -0.019287530332803726, -0.024942107498645782, -0.014407552778720856, 0.022463388741016388, 0.030829064548015594, -0.023237988352775574, -0.03284302353858948, 0.052672773599624634, -0.0024787187576293945, 0.017273571342229843, 0.010147254914045334, -0.01092185452580452, 0.027110986411571503, -0.024787187576293945, -0.006467906758189201, -0.009759955108165741, 0.024787187576293945, -0.03392746299505234, 0.01797071099281311, 0.05298261344432831, 0.03934966027736664, -0.005034897476434708, 0.03934966027736664, -0.009914875030517578, -0.0458562970161438, -0.029279865324497223, 0.00031468109227716923, -0.006777746602892876, 0.04647597670555115, 0.03284302353858948, 0.00435712281614542, 0.000547060975804925, -0.05515149235725403, 0.051433414220809937, 0.014252632856369019, -0.03113890439271927, 0.00013313430827111006, -0.04244805872440338, -0.0029628435149788857, 0.03888490051031113, 0.0229281485080719, -0.029589705169200897, 0.015491992235183716, 0.027575746178627014, -0.021378949284553528, -0.03532174229621887, -0.030674144625663757, 0.0162665918469429, -0.00491870753467083, -0.03423730283975601, 0.027420826256275177, 0.04430709779262543, 0.0567006915807724, 0.03609634190797806, -0.04523661732673645, 0.02509702742099762, 0.03423730283975601, 0.025716707110404968, -0.01680881157517433, 0.003117763437330723, 0.015569452196359634, 0.0032533183693885803, 0.011773914098739624, 0.0011328519321978092, 0.020604349672794342, -0.0054221972823143005, -0.00708758644759655, -0.0066228266805410385, -0.034547142684459686, -0.011386614292860031, 0.015182152390480042, -0.035786502063274384, 0.024322427809238434, 0.018435470759868622, -0.01471739262342453, -0.0012296768836677074, 0.0031371284276247025, -0.01363295316696167, -0.02664622664451599, -0.014794852584600449, -0.02013958990573883, 0.03857506066560745, 0.05391213297843933, 0.019829750061035156, -0.011773914098739624, -0.03826522082090378, 0.039504580199718475, 0.007978376001119614, -0.016731351613998413, 0.014097712934017181, -0.03315286338329315, -0.04089885950088501, 0.022618308663368225, 0.00654536671936512, -0.030364304780960083, -0.021533869206905365, 0.08117803931236267, 0.04802517592906952, -0.07591076195240021, 0.0075523462146520615, 0.040589019656181335, -0.028505265712738037, 0.0019752290099859238, 0.047715336084365845, 0.04213821887969971, 3.872998058795929e-05, 0.07312220335006714, 0.013710413128137589, 0.04430709779262543, 0.07095332443714142, -0.035166822373867035, 0.022618308663368225, 0.012083753943443298, 0.010224714875221252, -0.00817202590405941, 0.07405172288417816, -0.004105377942323685, -0.015027232468128204, 0.05081373453140259, 0.01254851371049881, 0.0029241135343909264, 0.018977690488100052, 0.0025949086993932724, 0.04399725794792175, 0.0066228266805410385, -0.041208699345588684, -0.014485012739896774, -0.02184370905160904, -0.016034211963415146, -0.015569452196359634, 0.011541534215211868, 0.0001258724369108677, -0.024167507886886597, -0.01688627153635025, 0.02509702742099762, 0.017893251031637192, 0.015569452196359634, 0.0010263444855809212, 0.021998628973960876, 0.010534554719924927, 0.04182837903499603, -0.016189131885766983, -0.07776980102062225, 0.03315286338329315, 0.03609634190797806, -0.002498083747923374, -0.012316133826971054, 0.009527575224637985, -0.04151853919029236, 0.04678581655025482, 0.08675515651702881, -0.01587929204106331, 0.0035050632432103157, -0.005577117204666138, 0.07157300412654877, 0.061348289251327515, -0.002285068854689598, 0.031913504004478455, -0.00045991851948201656, 0.07622060179710388, 0.06227780878543854, -0.04213821887969971, -0.003485698252916336, 0.01471739262342453, -0.009876145049929619, -0.012625973671674728, -0.06816476583480835, 0.03098398447036743, -0.03439222276210785, -0.008094565942883492, 0.023547828197479248, 0.03098398447036743, -0.0687844455242157, 0.01200629398226738, 0.04647597670555115, -0.0554613322019577, -0.007668536156415939, 0.00925646536052227, -0.008249485865235329, -0.02943478524684906, 0.01363295316696167, 0.035631582140922546, 0.07776980102062225, 0.002827288582921028, -0.013323113322257996, -0.03113890439271927, -0.01696373149752617, -0.003098398447036743, 0.0037955380976200104, -0.009217735379934311, -0.00546092726290226, 0.02075926959514618, 0.03330778330564499, 0.015646912157535553, -0.03609634190797806, 0.007010126486420631, 0.01742849126458168, -0.03996933996677399, -0.028195425868034363, 0.0026917336508631706, -0.038420140743255615, -0.028660185635089874, 0.010689474642276764, -0.007242506369948387, -0.03996933996677399, 0.011309154331684113, 0.005306007340550423, 0.0068939365446567535, -0.021998628973960876, 0.012161213904619217, 0.024322427809238434, -0.013168193399906158, 0.013555493205785751, 0.008830435574054718, 0.0034663332626223564, 0.011386614292860031, 0.00040666479617357254, 0.03609634190797806, 0.05391213297843933, -0.003872998058795929, 0.00983741506934166, -0.0554613322019577, -0.007707266137003899, 0.009488845244050026, -0.03005446493625641, -0.05948925018310547, 0.03206842392683029, 0.027110986411571503, 0.014485012739896774, -0.009488845244050026, 0.01587929204106331, -0.05019405484199524, 0.013478033244609833, 0.019519910216331482, -0.012316133826971054, -0.023083068430423737, 0.019210070371627808, -0.004473312757909298, 0.014562472701072693, -0.00017186428885906935, 0.009488845244050026, 0.01309073343873024, -0.02230846881866455, 0.005034897476434708, -0.017660871148109436, 0.015956752002239227, 0.008288215845823288, -0.047095656394958496, -0.013787873089313507, 0.041208699345588684, -0.022463388741016388, -0.02230846881866455, 0.04740549623966217, -0.05824989080429077, -0.004453947767615318, 0.022463388741016388, -0.0015685642138123512, -0.036716021597385406, -0.03284302353858948, -0.0325331836938858, 0.06661556661128998, 0.022463388741016388, 0.025716707110404968, 0.017583411186933517, -0.017893251031637192, -0.008055835962295532, -0.00925646536052227, -0.00708758644759655, 0.0013942793011665344, 0.005034897476434708, 0.020294509828090668, 0.006429176777601242, -0.04244805872440338, -0.0015588817186653614, -0.0040085529908537865, 0.021688789129257202, 0.004589502699673176, -0.008481865748763084, -0.006312986835837364, -0.054221972823143005, 0.015569452196359634, -0.017815791070461273, 0.035166822373867035, 0.017893251031637192, 0.03656110167503357, 0.0229281485080719, -0.020449429750442505, 0.000764917116612196, 0.019442450255155563, 0.047715336084365845, 0.019829750061035156, 0.029279865324497223, 0.03996933996677399, -0.010766934603452682, -0.047095656394958496, 0.03656110167503357, -0.003989188000559807, -0.004318392835557461, -0.013555493205785751, -0.04368741810321808, 0.03656110167503357, 0.004105377942323685, -0.01859039068222046, -0.012471053749322891, -0.010612014681100845, -0.03222334384918213, -0.017118651419878006, -0.04151853919029236, 0.04647597670555115, -0.0025949086993932724, 0.002827288582921028, -0.015027232468128204, 0.022618308663368225, 0.01037963479757309, -0.012703433632850647, -0.010844394564628601, 0.028660185635089874, -0.0097986850887537, 0.013013273477554321, 0.049264535307884216, 0.01859039068222046, -0.05019405484199524, -0.017893251031637192, 0.028195425868034363, -0.030209384858608246, 0.018280550837516785, -0.009217735379934311, -0.01254851371049881, -0.03718078136444092, -0.039504580199718475, 0.004182837903499603, -0.008598055690526962, -0.04182837903499603, 0.015182152390480042, -0.016653891652822495, 0.03222334384918213, -0.0030209384858608246, 0.0021495139226317406, -0.0002529551857151091, -0.01200629398226738, 0.04895469546318054, 0.035166822373867035, -0.06289748847484589, 0.01680881157517433, 0.021378949284553528, -0.005577117204666138, 0.0033501433208584785, -0.033462703227996826, -0.02339290827512741, -0.016189131885766983, 0.08737483620643616, -0.01634405180811882, 0.0283503457903862, 0.05298261344432831, -0.01642151176929474, -0.04523661732673645, 0.049264535307884216, -0.02989954501390457, 0.010844394564628601, -0.021378949284553528, -0.04430709779262543, 0.04523661732673645, -0.007048856467008591, 0.007591076195240021, -0.014097712934017181, 0.0025755437090992928, -0.004124742932617664, 0.013942793011665344, -0.026026546955108643, -0.0035244282335042953, 0.032378263771533966, -0.061348289251327515, -0.023547828197479248, -0.04802517592906952, -0.021688789129257202, 0.016189131885766983, 0.05298261344432831, -0.03175858408212662, 0.00035825232043862343, -0.018745310604572296, 0.0031758584082126617, -0.0010069794952869415, 0.00813329592347145, 0.03175858408212662, -0.03965950012207031, -0.0037955380976200104, 0.015956752002239227, -0.0097986850887537, -0.04151853919029236, 0.010999314486980438, -0.010457094758749008, 0.02013958990573883, 0.0026917336508631706, -0.008520595729351044, -0.030209384858608246, -0.04678581655025482, 0.01471739262342453, 0.019364990293979645, 0.02664622664451599, -7.503933738917112e-05, 0.005034897476434708, -0.04213821887969971, -0.0087529756128788, 0.006041876971721649, -0.0195973701775074, -0.006041876971721649, -0.05515149235725403, 0.044926777482032776, 0.07622060179710388, 0.0087529756128788, 0.030364304780960083, -0.022153548896312714, 0.032378263771533966, -0.011696454137563705, -0.016189131885766983, -0.04833501577377319, -0.04523661732673645, 0.025251947343349457, -0.02509702742099762, 0.034547142684459686, -0.044926777482032776, 0.024322427809238434, 0.011618994176387787, 0.04182837903499603, 0.02184370905160904, -0.006119336932897568, 0.028660185635089874, 0.05886957049369812, 0.06599588692188263, 0.02989954501390457, 0.0019849115051329136, -0.01037963479757309, -0.044926777482032776, 0.012703433632850647, 0.0038342680782079697, -0.01859039068222046, -0.041208699345588684, 0.05329245328903198, -0.019287530332803726, 0.1134013831615448, 0.009179005399346352, -0.0019945940002799034, 0.0325331836938858, -0.01905515044927597, 0.003117763437330723, -0.009759955108165741, -0.04213821887969971, -0.0020333239808678627, -0.04089885950088501, 0.02013958990573883, -0.03965950012207031, -0.01859039068222046, -0.052053093910217285, -0.02989954501390457, -0.08303707838058472, -0.03423730283975601, -0.00081817083992064, -0.03702586144208908, -0.03780046105384827, 0.02664622664451599, 0.0056933071464300156, 0.012161213904619217, -0.08365675806999207, -0.04151853919029236, 0.04895469546318054, 0.03888490051031113, 0.014252632856369019, -0.03113890439271927, 0.019519910216331482, 0.0038536330685019493, 0.008598055690526962, -0.03268810361623764, -0.02788558602333069, 0.035166822373867035, -0.015104692429304123, 0.0229281485080719, 0.0006729334127157927, 0.067545086145401, -0.009411385282874107, 0.024632267653942108, -0.06413684785366058, 0.011231694370508194, 0.06816476583480835, -0.02013958990573883, 0.0011909469030797482, 0.0391947403550148, 0.011696454137563705, -0.06196796894073486, -0.052672773599624634, 0.0554613322019577, 0.018203090876340866, -0.0034082382917404175, -0.009024085476994514, 0.0031952233985066414, -0.004570137709379196, 0.005383467301726341, 0.019364990293979645, -0.010302174836397171, -0.0175059512257576, -0.013323113322257996, 0.00654536671936512, -0.025251947343349457, -0.04244805872440338, -0.0028660185635089874, -0.0005712672136723995, -0.019442450255155563, -0.06723524630069733, -0.008830435574054718, 0.029744625091552734, 0.03749062120914459, -0.07591076195240021, 0.06599588692188263, -0.024942107498645782, -0.02013958990573883, 0.044926777482032776, -0.05019405484199524, -0.004415217787027359, -0.026336386799812317, -0.014407552778720856, -0.02618146687746048, -0.009488845244050026, 0.011154234409332275, 0.012161213904619217, 0.03780046105384827, -0.0025755437090992928, 0.02122402936220169, -0.018822770565748215, -0.024632267653942108, 0.09233227372169495, -0.0029047485440969467, 0.008636785671114922, -0.03005446493625641, 0.006041876971721649, 0.007513616234064102, -0.05824989080429077, -0.08303707838058472, 0.009914875030517578, -0.01254851371049881, -0.023083068430423737, 0.058559730648994446, -0.0032920483499765396, -0.018745310604572296, -0.009217735379934311, -0.011076774448156357, 0.021688789129257202, 0.029124945402145386, -0.037335701286792755, 0.06847460567951202, -0.010224714875221252, 0.03996933996677399, 0.0032339533790946007, 0.03656110167503357, -0.051433414220809937, 0.015956752002239227, -0.0017234841361641884, -0.008326945826411247, 0.06320732831954956, 0.015569452196359634, 0.012703433632850647, 0.03284302353858948, 0.07931900024414062, 0.006816476583480835, -0.013710413128137589, -0.03749062120914459, 0.03811030089855194, -0.10844394564628601, 0.031293824315071106, 0.09728971123695374, 0.028040505945682526, -0.0026336386799812317, 0.00435712281614542, -0.05824989080429077, -0.010224714875221252, -0.027575746178627014, 0.049884214997291565, -0.024632267653942108, -0.057010531425476074, -0.08303707838058472, 0.024632267653942108, 0.03888490051031113, -0.03439222276210785, 0.029744625091552734, 0.02509702742099762, 0.05019405484199524, 0.02075926959514618, 0.018125630915164948, -0.03934966027736664, -0.036251261830329895, 0.08365675806999207, -0.008443135768175125, 0.004996167495846748, -0.004453947767615318, -0.025871627032756805, 0.009992334991693497, 0.01642151176929474, -0.021378949284553528, 0.03857506066560745, 0.010612014681100845, -0.01642151176929474, 0.06723524630069733, 0.01735103130340576, -0.01688627153635025, 0.022463388741016388, 0.005073627457022667, 0.05081373453140259, -0.0005930528277531266, -0.0005664259660989046, 0.0567006915807724, 0.018822770565748215, 0.017196111381053925, -0.059179410338401794, -0.0072812363505363464, -0.04182837903499603, -0.047715336084365845, 0.004841247573494911, 0.03811030089855194, 0.0009682495146989822, -0.005267277359962463, -0.004260297864675522, 0.017893251031637192, -0.020449429750442505, -0.02447734773159027, -0.019364990293979645, 0.010069794952869415, 0.05732037127017975, 0.051433414220809937, -0.05824989080429077

In [59]:
# Amazon data
pointstructs = []
for i, data in enumerate(data_to_embed):
        embedding_vector = get_embedding(data['description'])
        pointstructs.append(
                PointStruct(
                        id = i,
                        vector=embedding_vector,
                        payload=data
                )
        )

In [ ]:
pointstructs

[PointStruct(id=0, vector=[0.011272362433373928, -0.05210698023438454, -0.025216033682227135, 0.016497185453772545, -0.04183842986822128, 0.018875135108828545, -0.002366486005485058, 0.023298516869544983, -0.0069670965895056725, 0.029055040329694748, 0.004387729801237583, -0.017302565276622772, -0.012977196834981441, -0.026297006756067276, 0.036894794553518295, 0.011561647988855839, 0.05056579038500786, -0.06331108510494232, 0.02936510369181633, -0.045794349163770676, -0.019177470356225967, -0.009072755463421345, 0.015938643366098404, -0.05210696905851364, -0.011950409971177578, -0.004672300536185503, 0.05598358437418938, -0.006347178481519222, -0.03240886330604553, 0.03264899551868439, -0.051971204578876495, -0.01515740342438221, 0.04154471307992935, -0.03105265460908413, -0.015630856156349182, 0.045289114117622375, -0.016751300543546677, 0.03467434644699097, -0.03734800964593887, 0.003195543307811022, -0.020759038627147675, 0.01831577531993389, -0.022193865850567818, 0.03236408159136772, 0.03221116214990616, 0.04905964061617851, 0.03847880661487579, -0.013871552422642708, -0.019703369587659836, -0.022120723500847816, -0.0034969027619808912, -0.022646205499768257, -0.0005518775433301926, -0.010930221527814865, -0.005729085765779018, 0.02383437007665634, 3.480870873318054e-05, 0.007068134378641844, -0.013131008483469486, 0.008268749341368675, 0.0548589788377285, -0.020006569102406502, -0.015177177265286446, 0.02161097340285778, -0.07412408292293549, 0.017689192667603493, -0.008410807698965073, -0.014940109103918076, -0.041746772825717926, -0.029609128832817078, -0.009798184968531132, -0.04786250367760658, -0.008302264846861362, 0.042432986199855804, -0.001758477301336825, -0.036152418702840805, -0.03080916590988636, 0.02168176881968975, -0.070268914103508, 0.058725979179143906, 0.005439505912363529, 0.006862684153020382, -0.02270386554300785, 0.021339356899261475, -0.014375559985637665, 0.02758626453578472, 0.009439828805625439, -0.029609760269522667, 0.04217306524515152, 0.03437674045562744, -0.008450755849480629, 0.004300553351640701, 0.026000751182436943, -0.013142935931682587, 0.010902381502091885, -0.030898885801434517, 0.006734752561897039, -0.031657151877880096, 0.01920195110142231, 0.03327604755759239, 0.03431431204080582, -0.05606625974178314, 0.01418348029255867, -0.012888003140687943, 0.02130524441599846, -0.036493051797151566, 0.021759020164608955, -0.010249576531350613, 0.011674124747514725, 0.007815361954271793, -0.0006581339403055608, -0.03693350777029991, 0.012006835080683231, 0.002246388467028737, -0.027286890894174576, -0.0738200768828392, -0.019070591777563095, -0.009145636111497879, 0.040672075003385544, 0.049303919076919556, 0.02060304954648018, 0.001740766572766006, 0.017345666885375977, -0.007959224283695221, -0.06778296828269958, 0.012861919589340687, 0.04421699792146683, -0.03183390200138092, -0.02649167738854885, -0.043481361120939255, -0.012565241195261478, 0.00847395695745945, -0.003431269433349371, 0.002770709805190563, -0.012505522929131985, 0.0011450361926108599, -0.007561212405562401, 0.006831835955381393, -0.013704176992177963, -0.01830608956515789, -0.0196530781686306, 0.033856213092803955, -0.05397827550768852, -0.0137899499386549, -0.002944003790616989, 0.02885311096906662, 0.010260429233312607, -0.051635436713695526, 0.016010761260986328, 0.03543144837021828, -0.017282888293266296, -0.0731382966041565, -0.029948826879262924, 0.04893631860613823, 0.011794016696512699, -0.005326783750206232, 0.037851765751838684, 0.01942940056324005, -0.02924467623233795, 0.05250932276248932, 0.007372870575636625, -0.004844655282795429, 0.029219819232821465, -0.016047092154622078, 0.029431911185383797, -0.049496378749608994, 0.04536306858062744, 0.030476002022624016, -0.0028254573699086905, 0.0074651590548455715, 0.027187326923012733, 0.023963691666722298, 0.0238207820802927, 0.03954773023724556, 0.004345954395830631, 0.005720657296478748, 0.06727313995361328, 0.02104247361421585, 0.02828432433307171, -0.016829155385494232, 0.038012269884347916, 0.0075370860286056995, -0.02452780306339264, 0.01756809651851654, -0.01907733827829361, -0.0068997349590063095, 0.020226899534463882, 0.011860465630888939, 0.025364262983202934, -0.0135842589661479, 0.0314822793006897, -0.04227185621857643, 0.04422001540660858, 0.01610587351024151, -0.027061089873313904, 0.004900116007775068, -0.02524142898619175, 0.022287676110863686, -0.014906961470842361, 0.06576008349657059, 0.06958435475826263, -0.041614241898059845, 0.04164130985736847, -0.05743612349033356, 0.020021840929985046, 0.05788039043545723, -0.04100066050887108, 0.0024040143471211195, 0.008354533463716507, 0.030748791992664337, -0.028216678649187088, 0.03563729301095009, 0.008840041235089302, -0.04789326712489128, 0.007926546968519688, -0.01821429841220379, 0.08142878115177155, -0.014340508729219437, 0.0156268160790205, -0.010303701274096966, -0.025416873395442963, -0.004579880274832249, 0.0805499330163002, -0.0420650988817215, -0.010867565870285034, -0.020603684708476067, -0.037291813641786575, 0.059030964970588684, 0.019811831414699554, -0.028602207079529762, -0.012399657629430294, -0.02550806663930416, -0.01876790262758732, -0.00944401416927576, 0.001507172710262239, -0.021609842777252197, 0.0026569529436528683, 0.043909091502428055, 0.043538276106119156, -0.014409348368644714, -0.013093572109937668, -0.019033074378967285, 0.0026959425304085016, -0.028435291722416878, 0.0006516805733554065, 0.02506750449538231, 0.03173781931400299, -0.020905684679746628, -0.009052292443811893, 0.017747147008776665, 0.020945481956005096, -0.011985856108367443, -0.025752520188689232, -0.008693809621036053, -0.001332312123849988, -0.01038725208491087, 0.01741129904985428, -0.010176488198339939, 0.015785343945026398, 0.048731617629528046, -0.021799033507704735, -0.008407342247664928, 0.03928769752383232, -0.026008397340774536, 0.051541853696107864, 0.03970347344875336, -0.004982059355825186, -0.02778092958033085, -0.01307468581944704, 0.015685899183154106, -0.0007687615579925478, 0.014782655984163284, -0.019513927400112152, -0.0058437129482626915, 0.02368522435426712, -0.06239227578043938, 0.0010163687402382493, -0.02231299690902233, -0.01865452714264393, 0.0038222961593419313, -0.024029621854424477, 0.007993132807314396, 0.02778649516403675, -0.0022513370495289564, -0.023485561832785606, -0.008463950827717781, 0.037951577454805374, 0.013746569864451885, -0.02309541404247284, 0.03955550864338875, 0.08692661672830582, 0.017625028267502785, 0.037607766687870026, 0.02773268148303032, 0.02499639429152012, -0.010626713745296001, -0.021562796086072922, -0.01667691394686699, -0.0015315552009269595, -0.057948850095272064, -0.0299360454082489, -0.01578274741768837, -0.03664136305451393, 0.04017104208469391, -0.0016570743173360825, -0.02660507895052433, -0.007243951316922903, -0.005523984786123037, -0.03944837674498558, -0.011629306711256504, -0.007209561299532652, -0.0043518394231796265, -0.02025463804602623, -0.00476441066712141, -0.00584034388884902, -0.03120790421962738, 0.08415299654006958, 0.08996862918138504, -0.0249189306050539, 0.0008486831211484969, 0.034815795719623566, -0.00705344183370471, -0.09464257955551147, -0.06879653036594391, -0.033215828239917755, 0.01041259616613388, -0.012227147817611694, 0.04822950437664986, 0.0027891609352082014, -0.0525168739259243, 0.024862222373485565, 0.04297834634780884, 0.027937456965446472, 0.021508021280169487, -0.00937313586473465, -0.032522112131118774, -0.030284395441412926, 0.010406818240880966, 0.0175864789634943, 0.009598858654499054, -0.0032325228676199913, -0.08407162874937057, 0.037002112716436386, 0.037069592624902725, 0.048614900559186935, -0.08118076622486115, -0.041041307151317596, -0.025479216128587723, -0.05316773056983948, 0.008397913537919521, 0.013649974018335342, -0.0062232171185314655, -0.08861847966909409, 0.04498805105686188, 0.028266459703445435, 0.028786571696400642, -0.02720499224960804, 0.037985172122716904, -0.04348915070295334, -0.009966446086764336, 0.0370345339179039, -0.03044147975742817, 0.07188450545072556, 0.022068925201892853, -0.027629699558019638, 0.04416794702410698, -0.0011639066506177187, -0.001148309907875955, -0.02701359987258911, -0.033195432275533676, 0.03351527452468872, 0.020757364109158516, 0.01735040731728077, 0.010278787463903427, -0.022439584136009216, 0.059782564640045166, -0.005838721990585327, -0.02880532294511795, -0.00811622105538845, -0.02960711158812046, 0.034364402294158936, 0.006928125862032175, 0.02669268101453781, 0.0048512909561395645, -0.04240982234477997, 0.03848510608077049, -0.009957530535757542, -0.04876316711306572, 0.004760567098855972, 0.03847673162817955, -0.028794489800930023, 0.011944878846406937, 0.04285072535276413, 0.01709107868373394, -0.014122867956757545, -0.04367191344499588, -0.0675886943936348, 0.08398273587226868, 0.029731430113315582, -0.0037738080136477947, 0.014749905094504356, 0.04743492975831032, -0.040313780307769775, 0.0003222722152713686, 0.0029488010331988335, -0.02401294745504856, 0.0023832551669329405, 0.011845663189888, -0.05792935565114021, 0.03432708978652954, -0.012381955049932003, -0.03336958587169647, -0.051145847886800766, -0.00180011335760355, 0.033575188368558884, -0.033670276403427124, 0.006569495424628258, 0.013008860871195793, 0.0296686552464962, -0.09063341468572617, 0.036962252110242844, -0.008385390043258667, -0.040206484496593475, -0.005665082484483719, -0.008757379837334156, 0.009032645262777805, 0.04323249310255051, -0.054444555193185806, 0.03759705275297165, 0.05136992782354355, -0.01156320609152317, 0.0008053791243582964, 0.0012408351758494973, -0.022934742271900177, 0.018551265820860863, 0.024471646174788475, -0.00857964064925909, 0.002401576144620776, -0.028216058388352394, -0.009684682823717594, -0.0011491456534713507, -0.01797027513384819, 0.03511960059404373, -0.05565577745437622, 0.03378256782889366, -0.05230171978473663, 0.004039526451379061, 0.02675376832485199, 0.0015595157165080309, -0.03281652554869652, -0.02305755764245987, -0.0013579672668129206, -0.09460482746362686, 0.009414576925337315, -0.028209958225488663, 0.028145838528871536, 0.022634357213974, -0.030773982405662537, -0.025497879832983017, -0.010761851444840431, -0.008792079985141754, 0.039128877222537994, 0.06711405515670776, -0.037950560450553894, -0.007411403581500053, 0.03632695972919464, -0.03137746453285217, -0.03895506635308266, 0.03481515124440193, -0.010926716029644012, -0.008489797823131084, 0.024346668273210526, 0.04808484762907028, -0.042267799377441406, -0.018130188807845116, 0.03194304183125496, -0.055579736828804016, -0.0023128408938646317, -0.008025050163269043, 0.03602192550897598, 0.03408120945096016, 0.006395334843546152, 0.026834897696971893, 0.004560580477118492, 0.038292281329631805, 0.03843382000923157, -0.01876300759613514, -0.021574541926383972, -0.005068334750831127, 0.005334178451448679, 0.01161715853959322, 0.012542074546217918, -0.011991875246167183, 0.003794874995946884, -0.019333403557538986, -0.042818110436201096, -0.0301675908267498, -0.031479302793741226, -0.022141648456454277, -0.055385854095220566, 0.04336869344115257, 0.05577079579234123, -0.0731734111905098, 0.008680409751832485, 0.07888767868280411, -0.04955342784523964, -0.042287252843379974, 0.027981458231806755, -0.01415727287530899, -0.014125320129096508, 0.023351559415459633, -0.028629278764128685, 0.002805469324812293, -0.004135385621339083, 0.07379747927188873, 0.03257318213582039, -0.0059550125151872635, 0.03163855895400047, 0.015483314171433449, 0.031136905774474144, -0.005217892583459616, -0.0349801667034626, 0.03012479841709137, 0.04195575788617134, -0.010919199325144291, -0.010492167435586452, -0.010668687522411346, 0.029674574732780457, 0.022668901830911636, 0.010005601681768894, -0.02549016661942005, 0.005160734057426453, -0.005087296478450298, 0.0016643734415993094, 0.034550439566373825, -0.026940520852804184, 0.016401760280132294, 0.030042549595236778, -0.0033024088479578495, -0.03220725059509277, 0.005464883521199226, -0.04619213938713074, -0.019689900800585747, 0.07290339469909668, -0.0013590905582532287, 0.03920384868979454, -0.018556933850049973, 0.0053574261255562305, 0.009694589301943779, -0.004137369338423014, -0.021732795983552933, -0.039964459836483, -0.028157059103250504, -0.021264199167490005, 0.036910153925418854, -0.017383506521582603, 0.01679193787276745, -0.0258475448936224, -0.00783008337020874, -0.026172049343585968, -0.01496836543083191, 0.023693198338150978, 0.002957491436973214, 0.011950094252824783, -0.07195626944303513, 0.0038282955065369606, -0.0015226021641865373, -0.0500623919069767, -0.049288537353277206, 0.01616533286869526, 0.01315444428473711, 0.0036926751490682364, -0.06043776869773865, 0.005863226018846035, 0.026104876771569252, -0.039636317640542984, -0.013901645317673683, -0.019280288368463516, 0.003350090468302369, 0.011523004621267319, 0.01608937792479992, -0.012646940536797047, -0.011845475062727928, 0.008827871643006802, -0.004257246386259794, 0.01744898408651352, -0.028539245948195457, -0.043168291449546814, 0.0013846285874024034, -0.03205784410238266, 0.02779216505587101, 0.044728316366672516, 0.004679844714701176, -0.017383430153131485, -0.01264180988073349, -0.04678177461028099, 0.022766023874282837, -0.005526901222765446, 0.03845750167965889, -0.01237904466688633, 0.03823002427816391, -0.005156959872692823, 0.019527971744537354, 0.023282457143068314, -0.015886340290308, -0.07013663649559021, 0.010937899351119995, 0.04926291108131409, -0.011342012323439121, -0.024121204391121864, 0.04143018648028374, -0.008152770809829235, -0.021057771518826485, -0.012577038258314133, -0.02086316980421543, 0.06827347725629807, -0.0036400281824171543, -0.011624284088611603, 0.00796265434473753, -0.009212787263095379, 0.030867740511894226, -0.02929523214697838, -0.0014977895189076662, -0.02212783321738243, 0.0007152747712098062, -0.0002195856795879081, 0.00080701126717031, 0.025477932766079903, -0.004516079556196928, 0.006542694289237261, 0.06928174197673798, -0.06506295502185822, 0.013458185829222202, 0.022317329421639442, -0.063086599111557, 0.04204317554831505, -0.0011175730032846332, -0.03146236389875412, -0.036435388028621674, 1.970563971553929e-06, -0.00809354055672884, -0.03952144831418991, 0.024950364604592323, -0.009725851938128471, -0.01777850277721882, -0.015015711076557636, 0.017479144036769867, -0.03825833275914192, -0.03007870726287365, -0.003924679942429066, 0.04819416627287865, -0.003929509315639734, -0.023239996284246445, -0.038057662546634674, -0.014131386764347553, 0.0016560505609959364, 0.03526397794485092, -0.0006775836227461696, 0.000739110226277262, -0.033124376088380814, 0.002013653051108122, 0.00512253912165761, 0.01621554233133793, -0.0306025929749012, 0.03550320118665695, 0.07411766797304153, 0.005763906054198742, -0.020063210278749466, -0.03927728906273842, -0.03897855430841446, 0.02830786257982254, 0.04400879889726639, 0.01924101822078228, -0.030614085495471954, -0.019318997859954834, 0.02471471205353737, -0.02514535002410412, -0.01944182813167572, -0.06911446154117584, 0.0033563654869794846, -0.020369162783026695, -0.06402512639760971, -0.001396415289491415, 0.012530115433037281, 0.009441855363547802, 0.033665165305137634, -0.0083362627774477, -0.028677769005298615, 0.005036511924117804, -0.03558189049363136, -0.015099482610821724, 0.060152776539325714, -0.02182467095553875, 0.03760446608066559, -0.013492035679519176, 0.06040084362030029, -0.02588813379406929, -0.02119310200214386, -0.023788750171661377, 0.013841385021805763, 0.06065938249230385, 0.027795296162366867, 0.024961289018392563, -0.007748810574412346, -0.012116128578782082, 0.03765362501144409, 0.020434292033314705, 0.026138687506318092, -0.030313510447740555, -0.028236204758286476, -0.010104438289999962, -0.02434462681412697, 0.01188080944120884, 0.04011000692844391, 0.019431309774518013, -0.014245877973735332, -0.005613153800368309, -0.08345255255699158, 0.016351381316781044, -0.012553215026855469, 0.004824363626539707, 0.07418104261159897, -0.010304893366992474, 0.0165301151573658, 0.007499675266444683, -0.036938175559043884, -0.0466247983276844, -0.02443976327776909, -0.057320643216371536, -0.0064118108712136745, -0.04412765055894852, -0.003917153924703598, -0.0319419763982296, -0.03595592454075813, -0.055176977068185806, -0.039986275136470795, -0.017818715423345566, 0.005724635906517506, 0.030363008379936218, -0.014606736600399017, 0.013992789201438427, -0.0202837772667408, 0.01911444216966629, -0.05182306841015816, -0.011002684012055397, 0.0036279556807130575, -0.05252794548869133, 0.030902165919542313, -0.005931892432272434, 0.009951184503734112, -0.03523711487650871, -0.035675227642059326, -0.035539913922548294, -0.02611302211880684, 0.02435755543410778, 0.03236502408981323, 0.026501081883907318, -0.022233281284570694, -0.001227215165272355, -0.014918661676347256, 0.03317338973283768, -0.042462121695280075, 0.027596263214945793, 0.021946363151073456, 0.0317867211997509, 0.007699829526245594, -0.03321785852313042, -0.01156245730817318, -0.02053716406226158, -0.013900045305490494, 0.011801534332334995, -0.0070671881549060345, -0.015600118786096573, 0.0015272836899384856, 0.011510131880640984, -0.024345772340893745, -0.06723063439130783, -0.021699873730540276, 0.013502003625035286, -0.012681128457188606, -0.03631710261106491, -0.010272959247231483, 0.0333305187523365, 0.031306274235248566, -0.014533803798258305, 0.013726769015192986, 0.02752397581934929, 0.0038794062566012144, 0.02188548818230629, -0.04555010050535202, 0.029351098462939262, 0.0022165884729474783, 0.00642692856490612, -0.0019254079088568687, -0.0708148255944252, -0.0057723610661923885, 0.05767501890659332, -0.051562096923589706, -0.008570395410060883, 0.017996858805418015, -0.04688096418976784, 0.01062006875872612, 0.028438538312911987, -0.0300961472094059, 0.03444773703813553, 0.023224804550409317, 0.013866555877029896, -0.04138105362653732, 0.006546359974890947, -0.02382206916809082, 0.003858715295791626, -0.02168554626405239, 0.02326647751033306, 0.08399579674005508, -0.023578843101859093, -0.025873687118291855, 0.03465856984257698, -0.039480067789554596, 0.007015509996563196, 0.005318173673003912, -0.04548608884215355, 0.005135459825396538, 0.006108419504016638, -0.0220318790525198, 0.030736396089196205, -0.031475383788347244, 0.00038822402711957693, -0.020619148388504982, -0.011800308711826801, 0.03874656558036804, -0.011651390232145786, -0.007326547056436539, 0.032721277326345444, -0.018851347267627716, -0.0069290949031710625, -0.025669865310192108, -0.003468362847343087, 0.02435610070824623, -0.013791345059871674, -0.007865210063755512, 0.02364361472427845, 0.045203305780887604, -0.014902685768902302, 0.023586003109812737, -0.035055436193943024, -0.018837744370102882, 0.01702062413096428, -0.014071673154830933, -0.04193717986345291, 0.04083471745252609, -0.08438065648078918, -0.006467719562351704, 0.019621258601546288, 0.024857567623257637, 0.011720653623342514, -0.007999593392014503, 0.02403981424868107, 0.00982430949807167, 0.007644995115697384, 0.029072387143969536, 0.003954688552767038, 0.04115496575832367, 0.047538191080093384, -0.00907568447291851, 0.050930947065353394, 0.0005538016557693481, 0.00012772780610248446, 0.05047880858182907, -0.025068096816539764, 0.03596719354391098, -0.020655686035752296, 0.042006488889455795, 0.02364170365035534, 0.02571089193224907, -0.022504771128296852, -0.0027565001510083675, 0.003529107430949807, 0.011699793860316277, 0.0010135875781998038, -0.024185245856642723, 0.018589545041322708, 0.012966169975697994, 0.0451226681470871, 0.01726551353931427, 0.05106892064213753, 0.05425344780087471, -0.0031442148610949516, -0.05458294600248337, -0.02604689821600914, -0.019814014434814453, -0.028459759429097176, 0.055820170789957047, 0.031835902482271194, 0.047319039702415466, -0.04152211919426918, -0.023081451654434204, 0.0032505837734788656, -0.017835093662142754, 0.043006788939237595, -0.016224144026637077, -0.024959970265626

In [61]:
len(pointstructs)

50

### Write embedding to qdrant

In [62]:
qdrant_client.upsert(
        collection_name = 'Amazon-items-collection-00',
        wait = True,
        points = pointstructs,
)

UpdateResult(operation_id=1, status=<UpdateStatus.COMPLETED: 'completed'>)

### Define retrieval from qdrant

In [65]:
def retrieve_data(query, k=5):
        """
        Get top k nearest data points from qdrant
        """
        query_embedding = get_embedding(query)
        results = qdrant_client.query_points(
                collection_name='Amazon-items-collection-00',
                query=query_embedding,
                limit=k
        )
        return results

In [66]:
retrieve_data("What kind of charging cords do you offer?", k=10).points

[ScoredPoint(id=38, version=1, score=0.54527074, payload={'description': '2022 Updated Digital TV Antenna to 500 Miles Range ', 'image': 'https://m.media-amazon.com/images/I/41sZZKxw3CL._AC_.jpg', 'rating_number': 131, 'price': None, 'average_rating': 3.4, 'parent_asin': 'B0B4WNFTVZ'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=20, version=1, score=0.52906954, payload={'description': 'Wireless Earbud, Bluetooth 5.1 Headphones with Microphone Deep Bass Bluetooth Earphones in-Ear, CVC8.0 Noise Cancelling Earbud for Sport Running Gym IPX7 Waterproof, 30H Playtime, Touch Control White ', 'image': 'https://m.media-amazon.com/images/I/41AmQP5zJ0L._AC_.jpg', 'rating_number': 457, 'price': None, 'average_rating': 4.1, 'parent_asin': 'B09F36P17Y'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=7, version=1, score=0.45518002, payload={'description': "iPhone Fast Charger, [Apple MFi Certified] 20W PD Type C Power Wall Charger with 3FT Lightning Cable Compatible with iPhone 13/13 Pro Max/12/12 Mini/12 Pro/12 Pro Max/11/11 Pro iPad AirPods 💌[One Charger, Lifetime Service] At Hcoob, you don't have to worry about after-sales problems, if you have any problems with the product, please let us know at any time, we will give you a satisfactory solution, we have confidence in our products and we are responsible to customers. 💪[3FT Apple Lightning Cable] The iphone charger sets includes 1*3 foot type c to lightning cable and apple 20W fast charger, which can charge your multiple apple devices and the charging speed is up to 3A. Let you spend less time used for charging and have more space for activities when it charge. Quick connect and High speed Data Transfer speed up to 480Mb/s helps you work efficiently. 👍[Orginal iphone High Speed Charger] Equipped with USB C Power Delivery port, PD 3.0 quick charge USB C port provides max 20w output power , latest-generation, future-proof fast charging technology, no error message pops up and works perfectly with your device while charging fast, 4X faster than regularly chargers. 💯[Applicable Apple Equipment] 100% With for iPhone13/13 mini/13 Pro/13 ProMax/iPhone 12/12 mini/12 Pro/12 ProMax/iPhone 11 ProMax/ 11 Pro/11/iPhone XS/ XS Max/ XR/ X/iPhone 8 Plus/ 8/iPhone SE 2020/iPad at fast speed , and charges for iphone 7Plus/7/6s Plus/6s/6Plus/6/5s/5/SE at an original charging speed. It also works with other USB C devices. ✅[Apple 20w Charger,Safety Assurance] Hcoob's ucb c fast charger built-in safety protection, which can monitor temperature and voltage in real time, maximize the protection of your device. The charger has a smart chip inside that actively adjusts the power output according to the needs of the device. As the battery is fully charged, the charging speed will be slower to give the battery time to absorb the charge and prevent the battery from rupturing.", 'image': 'https://m.media-amazon.com/images/I/3149HsGm0qL._AC_.jpg', 'rating_number': 802, 'price': 9.71, 'average_rating': 4.5, 'parent_asin': 'B0C6KVXZH9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=14, version=1, score=0.44190294, payload={'description': 'PEAPOLET iPhone Charger Cable, 3 Pack 3.3FT [Apple MFi Certified] USB-A to Lightning Cord Fast iPhone Charger Cable Compatible iPhone 14/13/12/11 Pro Max Xs X XR 8 7 iPad iPod 🌟【What You Get】 3PACK 3.3FT MFi Certified iPhone charging cables. 12 months free return and exchange service. We promise to solve all your problems. 🌟【Safe & Fast Charging】 Peapolet Lightning cable is composed of high-quality copper wires, which can output Safe and effective current for the device 🌟【Fast Charge & Data Transfer】 iphone Charger cord Supports safe Fast Charging (2.4A) and fast data transfer (480Mbps), Enjoy fast data transfer, syncing and charging 🌟【High-quality & durable】Carefully with high-quality TPE rubber material, the Lightning cable with 10000+times bend lifespan, which is strong and durable without entanglement 🌟【Perfect Compatibility】 Our USB Lightning cable with your USB Power Delivery charger (including Apple 29W, 30W, 61W or 87W USB-C power adapter) to charge your iOS device, supports fast charging for iPhone 13/13 Pro/12/12 Pro/11/11 Pro/11 Pro Max/X/XR/XS/XS Max, iPhone 8/8 Plus/7/7 Plus/6s/6s Plus/6/6 plus, iPad Pro, Airpods Pro and more', 'image': 'https://m.media-amazon.com/images/I/31b2pW8nb8L.jpg', 'rating_number': 496, 'price': 13.99, 'average_rating': 4.4, 'parent_asin': 'B09NCXYHMV'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=12, version=1, score=0.42045042, payload={'description': 'Arae USB Type C to 3.5mm Headphone and Charger Adapter, 2-in-1 USB C to Aux Audio Jack with PD 60W Fast Charging Dongle Cable Cord for Samsung Galaxy S22/S21/S20 Ultra, iPad Pro, MacBook, Pixel [Wide Compatibility] - Arae usb c headphone adapter compatible with most of the type c devices: Samsung Galaxy S22 S22+ S22 Ultra S21 S21+ S21 Ultra S20 S20+ S20 Ultra S20FE Z Flip, Note 20 10 10+, iPad Pro 2018/2020, MacBook Pro/Air, Pixel 4 3 2 XL, Huawei Mate 30 20 10 Pro, P30 P20 and more. [Multifunctional] - With the usb c headphone adapter, you can listen to your music while charging your phone. This multiple functionality usb c to 3.5mm audio adapter not only supports listening to music and answering calls, but also supports wired control functions, plug and play, without changing any settings. Let you use the simplest way to enjoy wonderful music anywhere. NOTE: Does NOT support data transfer. [Hi-Fi Sound Quality] - This headphone adapter adopted an advance DAC Smart Chip, offer high-definition audio, powerful noise reduction, you can get higher fidelity sound from it. [Supports Fast Charging] - Arae usb c headphone adapter and charger support up to 60w PD charging, you can listen to your music while charging your phone. NOTE: It may not support QC for some new phones. Suggest using PD wall charger to get faster charging speed. [Strong and Durable] - This cable can withstand more than 20,000 bending tests. The flexible nylon cable can withstand multiple bending and folding, and is not easy to damage.', 'image': 'https://m.media-amazon.com/images/I/41UhWTFtxzL._AC_.jpg', 'rating_number': 120, 'price': 19.99, 'average_rating': 4.4, 'parent_asin': 'B0BCKCJQPN'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=21, version=1, score=0.3913737, payload={'description': 'Togkun 2 Packs Earbuds Headphones Wired—Corded Ear Buds with Built-in Mic and Headphone Comfortable in-Ear Audifonos Earphones 【Save Time & Energy】 Ultra-portable Memory Function allows you just to turn on the Bluetooth before plugging in your earbuds for the first time. Then click "Connect with iCloud". They will connect automatically within 2-5 seconds next time if you plug in the earbuds feufain.', 'image': 'https://m.media-amazon.com/images/I/319s+2hyj+L._AC_.jpg', 'rating_number': 127, 'price': None, 'average_rating': 3.5, 'parent_asin': 'B0BS1GQJ5S'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=31, version=1, score=0.3650578, payload={'description': 'Harvopu iPad Air 5th 4th Generation Case with Keyboard - 7 Color Backlight Detachable Keyboard Tablet Cover with Pencil Holder for iPad Air 5th Gen 2022/iPad Air 4th Gen 2020 10.9, Sky Blue 【Wide Compatibility】This iPad keyboard case is designed for New iPad Air 5th Generation (Model Number: A2588/A2589/A2591), iPad Air 4th Generation (Model Number: A2316/A2324/A2325/A2072), Pro 11 1st Gen 2018 (A1980/A2013/A1934/A1979). Not for any other devices. Please be kindly check the model number No. starting with the letter "A" of your iPad back before order 【Detachable Wireless Keyboard】Designed for iPad air 5th/4th generation can be attached to the case with pretty strong magnets or detachable easily, can be an iPad or a Mac. Fast and stable bluetooth connectivity, reconnect automatically when turn on again once connected. It adopts scissor keys can quickly rebound and combines ergonomic unique concave design to achieve a true bass experience 【Rechargeable Long Life Keyboard】iPad air 5th generation keyboard built-in 380mAh high stability lithium-ion battery with energy-saving mode, no more worry about change battery. The Type-C charging port only 2 hours fast full charge to work for at least 168 hours, long stand by 800 hours, can travel with ease, which is good helper for office and business trip and the perfect choice worker and student 【Adjustable Viewing Angle & Support Charging Pencil Holder】This iPad air keyboard case built-in 3 anti-slip groove design of iPad air (4th, 5th gen - 2020, 2022) folio case provides multiple viewing angles whether you\'re typing or watching adjusts the iPad screen to suit your visual levels. Upper Pencil Slot for easy storage and charges directly if you place the 2nd Gen Apple Pencil 【Front and Back Protection】 The protective cover is made of durable faux leather, which is anti-fingerprint, wear-resistant and dirt-proof allows full access to all ports and protect iPas camera. The soft TPU back cover protects your iPad from scratches and damage, and interior with honeycomb design well in heat dissipation to extend life for your iPad 【Colorful Backlight Keyboard】The keyboard fonts are clearly visible, soft and not harsh when turn on backlit keys. Picture yourself typing smoothly in the dark using the optional backlight mode one color at a time or 7 colors breathing backlight,, which allows you to type smoothly in the dark even at night for work 【Rich Accessories & After-sales Service】You will get: 1 x iPad Case for iPad Air 4th/5th Generation, 1 x bluetooth keyboard, 1x Type C charging cable, 1 x user guide. If any questions about the model or function of our ipad keyboard case please feel free to click on the history order to contact us (via Amazon if exceeds the standard return window) and we will sincerely satisfactory solution for you', 'image': 'https://m.media-amazon.com/images/I/51qlRlNWivL._AC_.jpg', 'rating_number': 612, 'price': 32.98, 'average_rating': 4.5, 'parent_asin': 'B09QHYYMSF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=30, version=1, score=0.3500057, payload={'description': 'WAIRCO Airtag Holder - Ultra Secure Snap Closure Attachment for Clothing, Pet Collars, Luggage | Superior Protective Airtag Case for Children, Seniors and Pets Snap closure Versatile Utility: WAIRCO AirTag holder, with its grab and snap mechanism, easily attaches to all kinds of clothing, pet collars, luggage, backpack straps etc., making it the perfect solution for keeping track of kids, the elderly, pets, items and more. Better Protection: Our air tag holder has a strong, protective outer shell, precisely designed to protect your AirTag and keep it guarded against impact while staying firmly attached. Easy to Use: Simply fold the tab of this AirTag holder around clothing, dog collars, luggage and many other items, and firmly insert the snap mechanism. Your Snap Case is now ready to keep track of your loved ones and items. Unmatched Quality: This air tag case is made with premium quality, medical-grade materials to ensure the safety of children and pets. Our case protects your AirTag while allowing it to perform all of its functions such as tracking your items or hearing the AirTag beep during tracking. Customer Support: At WAIRCO, we believe in delivering complete satisfaction to our customers. Our AirTag accessories come with quick, comprehensive support so that you can keep tracking your loved ones and your special items and always have peace of mind.', 'image': 'https://m.media-amazon.com/images/I/51no3CkynQL._AC_.jpg', 'rating_number': 114, 'price': 14.99, 'average_rating': 3.9, 'parent_asin': 'B0BCN5S2W4'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=22, version=1, score=0.3463018, payload={'description': 'MOLOPPO for AirPods Max Case Cover, Clear Soft TPU Skin Anti-Scratch, Transparent Accessories Ultra Protective Cover for Apple AirPods Max(Clear Black) [Accurately Match] - The case cover accurately compatible with Airpods Max 2020(TIP: Airpods Max is not included) [Unique Design] - Snugly fits the AirPods Max Headphones without adding any additional bulk. It accurately handle every hole and edge, and enhance the comfortable experience. [High-quality Materials] - With skin-like surface and lightweight, premium clear soft anti-yellow TPU material offers full protection from scratches, accidental drops, bumps and shocks. [Easy to use] - It is easy to Install. The case cover will not adding any bulk and not affect put it in the storage bag. [Service] - We hope our service can bring you the perfect shopping experience. If you have any questions, please let us know and we will solve your problem as soon as possible.', 'image': 'https://m.media-amazon.com/images/I/41Fj7yVc2PL._AC_.jpg', 'rating_number': 1103, 'price': 9.99, 'average_rating': 4.7, 'parent_asin': 'B0C9X4HB3H'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=49, version=1, score=0.34346405, payload={'description': 'Eoved 302 Pcs Mixed Anime Stickers, Vinyl Waterproof Anime Stickers for Water Bottles, Laptops, Skateboards, Bicycles, Luggage. Gifts for Children, Men, Women, Teens, Adults. 【 Anime Stickers 】: The package contains 302 stickers of different styles. It includes 302 large stickers ranging in size from 2.5 "to 3.5". There are six different anime styles. 【High Quality Material】: These anime stickers are made of superior vinyl PVC material. The stickers are safe,non-toxic, waterproof and sun protection. High quality adhesives enable stickers to adhere firmly to the smooth surface of objects. Our stickers are not easy to fall off and can be reused without leaving traces. 【 Broad Application 】: Range of application is very broad. Decorating laptops, computers, track-pads / keyboards, water bottles, hydroflask, scrapbooks, mirrors, mac-books, notebooks, journals, luggage, skateboards, snowboards, bicycles, cars, and anything else that you can imagine. 【Best Gift】: Anime stickers must be a good choice for gift for anime stickers collectors, anime lovers, adults, friends, colleagues and kids.They must be so happy to recieve the Japanese classical anime stickers gift.Perfect as anime party decoration, party favors, reward supplies. 【Quality Service】: (NOTE：Rough surface, soft surface, abrasive particles, leather cloth surface are not applicable) .We are committed to providing every customer with the best products and services, as well as good shopping experience. If you have any questions, please contact us immediately.', 'image': 'https://m.media-amazon.com/images/I/61mFa9xbYYL._AC_.jpg', 'rating_number': 229, 'price': 9.99, 'average_rating': 4.7, 'parent_asin': 'B09NXCQMGS'}, vector=None, shard_key=None, order_value=None)]